### ISSUE TITLE
Format on save typically above 750 ms VSCode default timeout

### ISSUE THREAD

**Issue by joecorkerton** [elm-tooling/elm-language-client-vscode#10]
Really appreciate the effort that's gone into this!

One of the best features about Krzysztof-Cieslak/vscode-elm extension is the format on save option. Would you consider adding it to elmLS?

**Comment by joecorkerton** [comment]
So I discovered that VScode does have an option to automatically format on save. It also by default timeout of 750 milliseconds, and I now realise that most of the time the format was exceeding this limit (and hence not formatting). If I significantly increase the timeout then format works as expected.

So the issue seems to be more a combination of slow performance + the default vs code setting

**Comment by Razzeee** [comment]
Your likely affected by this https://github.com/avh4/binwrap/issues/31

**Comment by andys8** [comment]
Likely. See also https://github.com/elm-tooling/elm-language-server/issues/85.

@joecorkerton Can you post the output of  `time elm-format` and `which elm-format` if installed globally? (Not sure about the equivalent commands if you use windows).
If installed with npm I expect timings in the region of 0.4 seconds without doing anything. You can reduce it by downloading the binary from https://github.com/avh4/elm-format/releases and make in available on your `PATH`.

Also if this is an issue for you, maybe add a comment and some times for comparison to https://github.com/avh4/binwrap/issues/31. Thanks.

**Comment by joecorkerton** [comment]
Yes I have elm-format installed via npm

```
$ which elm-format
/usr/local/bin/elm-format

$ time elm-format (example Main file, ~1k LOC) --yes
real    0m0.311s
user    0m0.273s
sys     0m0.046s

$ time elm-analyse
real    0m1.294s
user    0m1.586s
sys     0m0.118s
```

I guess what I found strange is that Krzysztof-Cieslak/vscode-elm feels fast when it is running elm-format on save. For reference it's taking about 3 or 4 seconds for all the formatting to complete on the same file after saving, so it seems the bulk of the delay is not from elm-format. I guess the difference is due to elm-analyse also being run on save (among other things?)

**Comment by Razzeee** [comment]
There are some things, we do different compared to `Krzysztof-Cieslak/vscode-elm`.

Vscode-elm: Replaces the whole document with whatever elm-format generates. Which might reset your cursor to an arbitrary position, due to the language server not being able to know where you edited last.
elmLS: Actually diffs your code versus what elm-format generates. And only changes those parts. That way your cursor is less likely to move.

I would appreciate if someone can benchmark it, maybe even adding print statements to the language server. That way we will know which parts have the most potential to be improved.

Maybe we can improve the diffing, if that turns out consume a huge percentage. I just used a library from npm, that worked. Did not really test for performance back then.

**Comment by andys8** [comment]
My guess is that diffing is very fast compared to node loading required dependencies in the elm-format or if elm-analyse is executed (what @joecorkerton brought up). But measurement are the way to go.

**Comment by Razzeee** [comment]
So I benchmarked a bit, pretty simple file with about 1k lines.

Running elm-format took 0 seconds and 765207574 nanoseconds
Diffing afterwards took 0 seconds and 1442080 nanoseconds

All tests seemed to be like that. There is not much more that we're doing. So we will need to fix elm-format.

**Comment by joecorkerton** [comment]
@Razzeee what about elm-analyse? Is that run on save too or does it work a bit differently?

**Comment by Razzeee** [comment]
it's run, but not part of the formatting. it does use the format if you fix stuff,with elm-analyse.
but just saving only triggers diagnosntics being generated, which is completely separate.

**Comment by Razzeee** [comment]
Please continue discussion in https://github.com/elm-tooling/elm-language-server/issues/85
