### ISSUE TITLE
Refresh command

### ISSUE THREAD

**Issue by georgefst** [elm-tooling/elm-language-client-vscode#100]
Currently, if I make changes to, for example, my `elm-analyse.json`, the only way to get the extension to pick these up is to reload the whole window, thus disrupting my terminal sessions etc.

While one could try to monitor all potentially relevant config files, some other language clients provide a command (triggerable from the palette) allowing the extension to be manually restarted. e.g. `haskell-ide-engine` provides `Haskell: Restart HIE`. Something like this would be very useful.

**Comment by Razzeee** [comment]
Neat idea, thank you!

**Comment by georgefst** [comment]
Awesome, thanks!
