### ISSUE TITLE
<Ctrl + s> deletes source code.

### ISSUE THREAD

**Issue by IwateKyle** [elm-tooling/elm-language-client-vscode#102]
In VSCode, when I issue the keyboard shortcut Ctrl+s to save the current document the current source (.elm) file is all selected and deleted from the screen.  The response to Ctrl + 's' is the same as if I had issued Ctrl + 'a', followed by <delete>

## Expected Behavior

When I send the keystroke <Ctrl + s> , the current source file being edited should be saved to disk and left unchanged on the screen - or at most modified by the elm formatting tool

## Current Behavior
 The response to Ctrl + 's' is the same as if I had issued Ctrl + 'a', followed by delete

## Possible Solution
Currently, my VSCode is set to save files automatically, so the file *does* get saved.  However, not a long term solution.

## Steps to Reproduce (for bugs)

1. Install the elm-language-client-vscode plugin
2. create .elm file 
3. add elm code
4. issue <ctrl + s> keystroke

## Your Environment

VSCode 1.44.2
node 12.16.1
Ubuntu 19.10

**Comment by Razzeee** [comment]
I'm not sure why you mention your browser?

Can you try to disable format on save?

Also, can you share a code file that causes this behavior for you?

**Comment by IwateKyle** [comment]
You were correct - I didn't mean to say browser - I meant to say VSCode - I edited that part.  

As far a sample -?  Anything will do.  The content isn't the problem. It's simply the keystrokes of <CTRL-S> (Save file operation)  Any and ALL text in a document will be complete removed from the screen as if I selected it all the with mouse and deleted it.

**Comment by IwateKyle** [comment]
Ah !  After I disabled format on save - the problem doesn't happen any longer.  Of course now my other documents don't have format on save now.

**Comment by IwateKyle** [comment]
After further investigation - went back and re-noticed something.  During the installation of the plugin - there were instructions to install the elm-format which caused a hanging point - my bash shell didn't return.  This happened a couple of times.  I used (Ctrl-c) to escape.  Then I tried to run the format program and it didn't complain so I thought it was working when it hadn't actually been installed properly.

Just now I tried again and waited a little bit longer and the shell finally returned.  There was some sort of processing happening there for a while.  So apparently VSCode wasn't finding the format program and farted on my code.

**Comment by Razzeee** [comment]
Interesting, did you run elm format manually by chance? I'm curious what it
returned.

**Comment by IwateKyle** [comment]
Yes, I ran elm-format from the command line after having to manually break out of the installation.  I wasn't getting any errors - so I interpreted things as being fine.

**Comment by Razzeee** [comment]
Not sure we can prevent this then :/

**Comment by IwateKyle** [comment]
I'll close the issue then.  Thanks for taking a look into it.
