### ISSUE TITLE
vs code renderer CPU consumption

### ISSUE THREAD

**Issue by yarus23** [elm-tooling/elm-language-client-vscode#104]
Have you noticed that process named Code Helper (Renderer) eats 100% CPU?
It is a common issue for vscode. I have got only elm plugin installed.

## Your Environment

* Version used:
* Editor name and version (e.g. VSCode 1.36.1): vscode 1.44.2
* Operating System and version: MacOS 15.4

**Comment by Razzeee** [comment]
Can't replicate. Do you see this in the "Process explorer" in Vscode itself?

**Comment by yarus23** [comment]
In process explorer I see "electron_node index.js" eats all cpu

**Comment by yarus23** [comment]
Disabling the extensions removes cpu consumption.
BTW I use big file in my project from there https://github.com/elm-tooling/elm-language-client-vscode/issues/89

**Comment by Razzeee** [comment]
Using that project, I can't get anywhere near your CPU usage. Are you doing anything specific when it starts?

**Comment by yarus23** [comment]
Try after opening the project open in editor file TLWND.elm you will see processor consumption spike

**Comment by Razzeee** [comment]
Is this happening for you with elm-analyse decativated? Like mentioned in https://github.com/elm-tooling/elm-language-client-vscode/issues/89#issuecomment-602308485

**Comment by xinaesthete** [comment]
I see a similar thing here on my machine - 13% CPU i.e. one core maxed out & quite a while before it was finished.  Actually, after deleting TLWND.elm it was still churning away; necessary to restart the VSCode window, or wait quite a while before code-completion etc work.

**Comment by Razzeee** [comment]
@yarus23 as you opened an issue over at elm-analyse, can I close this one?

**Comment by yarus23** [comment]
I change "Elm Analyse Trigger" to "on save"
