### ISSUE TITLE
Goto commented definition instead of real one

### ISSUE THREAD

**Issue by AlienKevin** [elm-tooling/elm-language-client-vscode#106]
## Expected Behavior
The real definition always has a higher priority than commented out one.
Goto the real definition regardless of source order.

## Current Behavior
If the commented out definition appears before the real one, goto navigates to the commented out one.

## Possible Solution
Distinguish between commented-out and real definition.

## Steps to Reproduce

1. Copy a definition, put it **before** the original definition, and comment out the copy
2. Control-click on a name that refers to the definition
3. Arrives at the commented out definition

## Your Environment

* Version used: 0.10.2
* Editor name and version: VS Code 1.45.0
* Operating System and version: Windows Subsystem for Linux 2 in Windows 10

**Comment by Razzeee** [comment]
I'm not sure if I understood you right, I fail to replicate this problem.

![Peek 2020-05-21 11-28](https://user-images.githubusercontent.com/5943908/82544970-39f3e780-9b56-11ea-86f3-ef7c00683ed3.gif)

**Comment by AlienKevin** [comment]
Sorry, I forgot to save a copy of the example I encountered. I will close this issue for now.
