### ISSUE TITLE
elm-format fails

### ISSUE THREAD

**Issue by eratio08** [elm-tooling/elm-language-client-vscode#107]
## Expected Behavior

format file when saving or calling format action manually

## Current Behavior

formating fails with 
```log
[Warn  - 13:12:09] {"shortMessage":"Command failed with exit code 127: elm-format --stdin --elm-version 0.19 --yes","command":"elm-format --stdin --elm-version 0.19 --yes","exitCode":127,"stdout":"","stderr":"env: node: No such file or directory\n","failed":true,"timedOut":false,"isCanceled":false,"killed":false}
```
`elm-format` is installed globally, also tried locally and explicit path in settings - same error with different path before `elm-format`

## Steps to Reproduce (for bugs)

1. Setup project like proposed in readme
2. Execute Format action of vscode
3.
4.

## Your Environment

* Version used: 0.10.2
* Editor name and version (e.g. VSCode 1.36.1):  VSCode 1.45.1
* Environment name and version (e.g. node.js 5.4): nodejs v14.3.0, elm 0.19.1
* Operating System and version: macOS 10.15.4

**Comment by Razzeee** [comment]
are you able to call `elm-format` on your cmd? did you install it via npm or did you download the release (https://github.com/avh4/elm-format/releases/tag/0.8.3) and put in in you path?

**Comment by eratio08** [comment]
It's on the path, and I'm able to call it manually. Which is formatting the file successfully.

**Comment by Razzeee** [comment]
Can you try to reinstall it? We recently had someone who thought it got stuck on install and aborted it and it still was callable from path.

**Comment by eratio08** [comment]
Check, un- and re-instaling did the job! Thx!

**Comment by kewp** [comment]
I'm having the same issue - I've tried installing / reinstalling. I think it may have to do with nvm (sic) for windows https://github.com/coreybutler/nvm-windows which managed my node version (so, for example, if I try to uninstall `elm-format` it is still there which might be because of nvm https://github.com/npm/npm/issues/17905)

**Comment by kewp** [comment]
Hmm, no dice. I managed to uninstall `elm-format` (by removing any references to npm from my path variables, i.e. allowing nvm to take over) and reinstalling. Then uninstall / reinstall the VS Code plugin. Still nothing.

**Comment by Razzeee** [comment]
Did you try to set the path explicitly?

**Comment by kewp** [comment]
Hi @Razzeee . I’m not sure what you mean, set the path where? In the environment variables?

**Comment by Razzeee** [comment]
In the vscode settings for the plugin. `Ctrl + ,` then search for elm.

**Comment by kewp** [comment]
Hi @Razzeee . Sorry, I know those settings. But what path am I suppose to put, and into which elm setting?

**Comment by Razzeee** [comment]
I would try to set the elm-format path to the path where nvm keeps your elm-format installation.

**Comment by kewp** [comment]
Hi @Razzeee . Again, I'm sorry but I think we are talking past one another. I don't know how to set the elm format path. I'm assuming you're talking about the elm section of `settings.json` in VS code but I don't know which setting to use. I've searched for it and the only setting I know of is `formatOnSave` (which is on).

**Comment by kewp** [comment]
Ok so I've found the setting in the plugin homepage https://marketplace.visualstudio.com/items?itemName=Elmtooling.elm-ls-vscode and then I had to confirm I had access to it by using CTRL+space to show it up (I couldn't tell if it was suppose to be in tlem `[elm]` section? Answer: no, it must be on it's own). But I've tried all manner of combinations (do I need to reload VS code?) and still nothing.

```
"elmLS.elmFormatPath": "C:\\Program Files\\nodejs\\elm-format.exe"
```

Isn't there a place I can see the console logs of the plugin?

**Comment by Razzeee** [comment]
When in the `Output`-Panel, select `Elm` from the dropdown on the right. If it's not showing up in that list, the server hasn't been started, go and open an elm file in that case.

**Comment by kewp** [comment]
I don't see Elm in the drop-down.

![elm dropdown](https://user-images.githubusercontent.com/396394/99580256-ef113a80-29e7-11eb-9782-b6cb87c91a95.png)

**Comment by kewp** [comment]
Hey @Razzeee . Both are correct I'm afraid. I've tried opening the elm SPA example - same result.

Is there no way to look at, I dunno, the language server? How can I figure out why it's not loading?

![elm tooling](https://user-images.githubusercontent.com/396394/99641325-c6725a80-2a52-11eb-9415-592909b01dc2.png)

![elm dropdown 2](https://user-images.githubusercontent.com/396394/99641346-cd00d200-2a52-11eb-9f9f-c25b7eb34ffb.png)

**Comment by kewp** [comment]
Hey @Razzeee I got it working!

It works when I open the folder of my project, i.e. File -> Open Folder... from VS code. Then I see Elm in the Output window drop-down.

Formatting on save didn't work at first, but I _did_ see a message saying "Run `npm install -g elm-format`". That didn't work - what did was clearing the Elm Format Path setting that I had set earlier. Now it formats on save! And I have suggestions working too!

Thanks for the help.

**Comment by kewp** [comment]
Just setup a new machine and having the same issue. `elm-format` doesn't run when I save.

- I've tried uninstalling / reinstalling the VS code plugin
- I can run `elm-format` from the command line
- I have a `elm.json` in the root folder
- I also have a `elm-tooling.json` in the root folder
- I've open the project folder up in VS code (see my solution previously)
- I've tried several different `.elm` files. Same result
- I've tried setting the Elm Format Path directly

Not sure what else to try.

The Elm output in VS code looks fine. No mention of `elm-format`, though.

```
[Info  - 14:48:57] Find entrypoints: Using entrypoints from c:\Users\karlp\elm-aws\elm-tooling.json: ["./src/ElmUITest.elm"]. See https://github.com/elm-tooling/elm-language-server#configuration for more information.
[Info  - 14:48:57] A code lens resolve was requested for file:///c%3A/Users/karlp/elm-aws/src/LoadTest.elm
[Info  - 14:48:58] A code action was requested
[Info  - 14:48:58] Document Symbols were requested
[Info  - 14:48:58] Folding ranges were requested
[Info  - 14:48:58] Returned 8 folding ranges
[Info  - 14:48:58] A code lens was requested for file:///c%3A/Users/karlp/elm-aws/src/ElmUITest.elm
[Info  - 14:48:58] A code action was requested
```

**Comment by Razzeee** [comment]
You changed the vscode config to enable format on save?

**Comment by kewp** [comment]
Ok. Yes - I just set it, and it worked :). Thank you.
