### ISSUE TITLE
Feature request: compile Main.elm on submodules changes

### ISSUE THREAD

**Issue by rogeriochaves** [elm-tooling/elm-language-client-vscode#114]
## Expected Behavior

When I change a submodule, like Model.elm, I'd like for the plugin to compile not just my module but also Main.elm, that wayI can know everything else that broke. If I'm not mistaken vscode-elm could do that

## Current Behavior

I only see compilation error messages for current module

## Possible Solution

Add a field in configuration for optionally providing a path to Main.elm file, that could be triggered every time a save in any other .elm file is triggered

## Context

Right now I only see errors in webpack console, or on the browser, so I lose the IDE integration unless I open Main.elm, save and edit manually

## Your Environment

* Version used: v1.2.0
* Editor name and version: VSCode 1.48.1
* Environment name and version: nodejs 14
* Operating System and version: macOS Catalina

**Comment by Razzeee** [comment]
https://github.com/elm-tooling/elm-language-server/issues/118

**Comment by rogeriochaves** [comment]
cool, I'll close this one then
