### ISSUE TITLE
nested let statements break code folding

### ISSUE THREAD

**Issue by smarwei** [elm-tooling/elm-language-client-vscode#115]
When nesting at least two let statement, code folding breaks. Sometimes clicking the folding icon will even collapse multiple functions.  

## Expected Behavior
- every function should be collapsible
- no collapsing in a code block

## Current Behavior
- the first let statement is collapsible, the function itself is not. 
- in the nested let statement code blocks can be collapsed in weird ways
![nesting](https://user-images.githubusercontent.com/9263007/94341422-73a79400-0009-11eb-85d3-82a97e11e892.png)

## Steps to Reproduce
`
module Nesting exposing (..)

testNesting : String -> Maybe String
testNesting color0 =
    let
        color = String.toLower color0
    in
    if color == "black"
        then
            let 
                c = "Black"
            in
            Just c
    else if color == "white"
        then Just "White"
    else Nothing
`

## Your Environment
* Version used: 1.3.0
* Editor name and version:  VSCode 1.49.2
* Environment name and version: elm 0.19.1
* Operating System and version: Ubuntu 20.04.1 LTS

**Comment by Razzeee** [comment]
I'm actually getting way more (and different folds). Can you still replicate that with a fresh vscode instance?

**Comment by smarwei** [comment]
When I opened the file in a seperate workspace the problem was gone. 
It seems like it only occurs if the code is referenced in source-directories in elm.json. 

I created a minimal example that always triggers the problem for me:
[https://github.com/smarwei/nesting](https://github.com/smarwei/nesting)

Is this working for you as well?

**Comment by Razzeee** [comment]
There is something about how you wrote this, that breaks our parser it seems. The space after the second `let` plays a roll in this.

This is also parsed as one function, which is a problem.
```
c = "Black"
            in
            Just c
```

If I run elm-format on it, it get's indented differently, cleaned up and that fixes folding. I'm still on the old elm-format version, so that might play a part here.

Will have to be fixed in the parser repo.

**Comment by Razzeee** [comment]
https://github.com/Razzeee/tree-sitter-elm/pull/46 should help with this

**Comment by smarwei** [comment]
I noticed that having let and a definition in the same line has the same problem. 
So the newline does not seem to be the root of the problem:
https://github.com/smarwei/nesting/blob/master/src/Let.elm

**Comment by Razzeee** [comment]
Should work with https://github.com/Razzeee/tree-sitter-elm/pull/48

**Comment by Razzeee** [comment]
Should be better now, just release a new version. I think there is still a problem with how it folds in the `let` case your posted.
