### ISSUE TITLE
Auto import

### ISSUE THREAD

**Issue by blinaa** [elm-tooling/elm-language-client-vscode#117]
I have an import exposing some elements:
```import Element exposing (Element, row)```
when i auto import not exposed element from this module, it creates a new import, and i have something like:
```
import Element exposing (Element, row)
import Element exposing (image)
```

## Expected Behavior
```import Element exposing (Element, row, image)```

## Context
I think adding an element to the existed queue is better than creating a new import line, if you don't agree with me, let me know why.

## Your Environment
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:10:24.511Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.52

**Comment by Razzeee** [comment]
Hey there,

elm-format will merge these, that's basically why we don't figure these out for you at the moment. So either activate `Format on save` or run format on your own.

We could consider doing this correctly, but I think there are things, that we'll likely do first.
