### ISSUE TITLE
Hovering on function does nothing instead of showing function signature (or docs)

### ISSUE THREAD

**Issue by aszenz** [elm-tooling/elm-language-client-vscode#118]
## Expected Behaviour
Hovering on function is expected to show the function signature but it shows nothing, hovering over types does work though

## Current Behaviour

Hovering over a function name should provide its signature and documentation in a dialog box

## Your Environment

VSCode Version: 1.49.3
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic snap

**Elm Plugin Version: 1.4.0**

**Comment by Razzeee** [comment]
Sorry for this, there is a hotfix enroute to fix this.

**Comment by Razzeee** [comment]
Should be fixed now, if you grab the latest version.

**Comment by aszenz** [comment]
Thanks for the hot fix, confirmed working in version v1.4.1 of the plugin.
Closing this issue now
