### ISSUE TITLE
Hangs if file ends in empty comment

### ISSUE THREAD

**Issue by nonpop** [elm-tooling/elm-language-client-vscode#12]
**EDIT:** moved to tree sitter repo

arch linux, vscode 1.36.1, ElmLS 0.3.0

Create a new project with `elm init` and create `src/Foo.elm` with the following contents:
```elm
module Foo exposing (foo)
foo = 42
--
```
Make sure there is no newline after the dashes, use save without formattig if necessary. Restart vscode. Now the client/ls hangs with 100% cpu usage. Closing vscode does not kill the halted process. If this file exists then opening vscode will start consuming 100% cpu even if the file itself is not opened. Adding a newline after the comment fixes the problem.

**Comment by Razzeee** [comment]
Good find. Can you move this issue here https://github.com/Razzeee/tree-sitter-elm ?
