### ISSUE TITLE
No formatter found for Elm after upgrading to v1.5.0

### ISSUE THREAD

**Issue by klemola** [elm-tooling/elm-language-client-vscode#121]
## Expected Behavior
I expected the new version to automatically format elm files, if elm-format is installed and in PATH

## Current Behavior
Nothing happens, and when I run the "Format document" command manually, VS Code says that there's no formatter for Elm installed. The previous extension version works as expected.

## Possible Solution
Sounds like a regression. Maybe the plugin is not registered as a formatter to VS Code anymore?

## Steps to Reproduce (for bugs)
1. Update to 1.5.0
2. Make a change to an .elm file that is not properly formatted
3. Save the file
4. See that the code is still unformatted

## Context
-

## Your Environment
* Version used: 1.5.0
* Editor name and version: VS Code 1.50.1
* Environment name and version:  elm 0.19.1, elm-format 0.8.3, nodejs 12.18.4
* Operating System and version: Windows 10 20.04 +, WSL 2

**Comment by Razzeee** [comment]
Should be better now, we were testing a new release workflow and had an oversight.

**Comment by klemola** [comment]
> 
> 
> Should be better now, we were testing a new release workflow and had an oversight.

✅ Yeah, works again with v1.5.2. Thanks for a speedy fix!
