### ISSUE TITLE
Show actual error/tips on type, not on save

### ISSUE THREAD

**Issue by whitecolor** [elm-tooling/elm-language-client-vscode#124]
So I believe this is a feature request, though wonder why it is not implemented.

## Expected Behavior
Errors and helpful tips will be shown whenever you type in a file. This is the behavior many used to real-time IntelliSense, not just no file save.

## Current Behavior
> Errors and helpful tips will be shown whenever you save a file (Control + S)

Analysis and results are done only when the file is saved.

**Comment by Razzeee** [comment]
I'm assuming your speaking of the elm compiler errors. This isn't possible, as the compiler is only able to act on files that have been written to your disk. If you care for this, please make it known with the people who are writing the compiler.

However, we're working on showing some similar info on typing, basically what we know through type inference, but likely we won't be able to show as nice error messages as the compiler offers.

Closing, as I don't think we can act on this.

**Comment by whitecolor** [comment]
> This isn't possible, as the compiler is only able to act on files that have been written to your disk.

This is kind of strange. Do you know what is the reason for this? You probably already applied with the problem?

**Comment by whitecolor** [comment]
@Razzeee 
Didn't you think to add an autosave feature in the plugin? As vscode doesn't support per language autosave.

**Comment by Razzeee** [comment]
> This is kind of strange. Do you know what is the reason for this? You probably already applied with the problem?

I'm not sure, I think it just never was considered/implemented. The Elm maintainers are unfortunately not very ide/tooling savy.

> Didn't you think to add an autosave feature in the plugin? As vscode doesn't support per language autosave. Though it is probably out of plugin's scope.

I think VIM is doing this, but I wouldn't encourage this, as it seems to not be very nice. As holding it in memory should be way faster then waiting for your HDD to be ready to write and have actually written. (think of old systems or less powered)

Anyway vscode offers this setting, which you can set to `afterDelay`

![image](https://user-images.githubusercontent.com/5943908/97456946-96df9f00-1939-11eb-9837-fc2350aecea7.png)

**Comment by whitecolor** [comment]
> Anyway vscode offers this setting, which you can set to afterDelay

As I said it doesn't allow to have this setting per file type, it is actual when in the workspace I have files that should not be subject for autosave =).  Actually, I tried to work write elm with autosave in vscode, it seems to work quite well in realtime.

Of course, it would be better if the compiler supported for example virtual file system, that could be used by plugins and extensions.
