### ISSUE TITLE
Couldn't start client Elm

### ISSUE THREAD

**Issue by kewp** [elm-tooling/elm-language-client-vscode#125]
The plugin isn't working for me. I've installed it (v1.5.2) but nothing happens when I save (no formatting).

I also see errors pop-up (see image).

![vscode_error](https://user-images.githubusercontent.com/396394/97408652-1010cf00-1905-11eb-84ab-b246d91297d9.png)

I've installed elm with npm (1.9.1). I've also installed `elm-format` and `elm-test` globally.

* VS Code 1.50.1
* Node 12.18.3
* NPM 6.14.6
* Windows 10

**Comment by kewp** [comment]
When I placed a `elm.json` into the folder (as suggested...?) the errors do go away. But it's not doing a format on save...

**Comment by kewp** [comment]
Hmmm OK so I added this to the settings

```
"[elm]": {
    "editor.formatOnSave": true
},
```

as suggested here https://stackoverflow.com/a/61201368/4295424
and the format on save is now working (though I expected it was enabled by default?)

**Comment by Razzeee** [comment]
> and the format on save is now working (though I expected it was enabled by default?)

depends on your vscode settings, I can't speak for these, as microsoft decides, what the default is

**Comment by kewp** [comment]
Hmm I see. Thanks @Razzeee . And I see in the readme it says you need a `elm.json`. All is working now so closing the issue.
