### ISSUE TITLE
Support client diagnostic requests and cancellation

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-client-vscode#127]
Because the language server runs in a single process, we cannot add this to the server directly but we can gain some extra performance by adding it to the client.

The idea is that the client would request diagnostics along with a cancellation token. Then, if another, more urgent request comes through (completion, hover, formatting, etc), we can cancel the long running diagnostics request and trigger it again after the urgent request is sent. This will make formatting and completions requests resolve much quicker because they won't be waiting on the type checker to run diagnostics on the entire file.

I've been modeling this after the Typescript language support in VSCode with the tsserver, so I think it is a solid design. 

This would be an opt-in capability that the client would specify to signal that it will handle diagnostic requests. Otherwise, the server will continue to ask for diagnostics on change, like we do today.

**Comment by Razzeee** [comment]
Would this be easier, if we move it out of process? Would that enable cancelations for other clients too?

**Comment by jmbockhorst** [comment]
Move what out of process?

**Comment by Razzeee** [comment]
The language server

> Because the language server runs in a single process

**Comment by jmbockhorst** [comment]
It didn't really seem very feasible to me.

**Comment by jmbockhorst** [comment]
I guess you would have to run a middle "proxy" server that passes messages through to the real server and handle diagnostics and cancellation.

**Comment by Razzeee** [comment]
@jmbockhorst do you think this is done now?

**Comment by jmbockhorst** [comment]
We can close for now but I might revisit in the future.
