### ISSUE TITLE
When file with an error is already opened in editor it doesn't show diagnostics

### ISSUE THREAD

**Issue by wclr** [elm-tooling/elm-language-client-vscode#128]
## Expected Behavior
If one launches editor or restarts lang server opened editors with elm files should show diagnostic errors. Check probably should happen when the editor tab with the file is visible/active.

## Current Behavior
Doesn't show until the file is edited and saved. If a tab with a file was not active, making it active doesn't affect the result.

## Steps to Reproduce (for bugs)
1. Reopen editor/relaunch lang server with opened elm file.

**Comment by whitecolor** [comment]
Should probably run compilation for all entry points on start, to get the errors in the project.

**Comment by Razzeee** [comment]
It might be easy to do, but I'm not sure if it will break stuff. I would be willing to merge something properly tested for this.

**Comment by Razzeee** [comment]
This should be the case with the next release
