### ISSUE TITLE
Issue with files name cases.

### ISSUE THREAD

**Issue by whitecolor** [elm-tooling/elm-language-client-vscode#129]
I had the same issue: https://github.com/elm-tooling/elm-language-client-vscode/issues/123

I've debuged it, so the reason is that vscode has some buggy behavior with files that changed name cases (were renamed) and file `uri` inside DiagnosticsProvider is not normalized, so it results that it can not find it in `currentDiagnostics` map.

![image](https://user-images.githubusercontent.com/736697/97759326-9f46fe00-1b22-11eb-89e9-40ed6b706773.png)

**Comment by Razzeee** [comment]
Can you recheck this with the new version?

Also could you please use the issue template, this issue is very hard to understand/not very good explained.

**Comment by whitecolor** [comment]
> Also could you please use the issue template, 

I could but it woudn't add much.

The issue happens where one renames file changing letter case. For example `main.elm` -> `Main.elm`, vscode treats it inconsistently, though in filesystem file is `Main.elm`, but vscode displays and treat it like `main.elm`, probably this causes the inconsistency due to what the extension in different places has URI file path either `main.elm` or `Main.elm` at the same time.

**Comment by Razzeee** [comment]
Not reproduce-able, I did try on linux. Seems fine here, closing for now, as we don't have any more info.

**Comment by whitecolor** [comment]
This probably only windows related issue, as Linux and windows treat file name cases differently.

**Comment by Razzeee** [comment]
Which is something the issue template asks for. And a step by step
reproduction.
