### ISSUE TITLE
The last error is not cleared when there is entrypoint set

### ISSUE THREAD

**Issue by whitecolor** [elm-tooling/elm-language-client-vscode#130]
## Expected Behavior
All not actual errors are cleared in modules and entry point.

## Current Behavior

Error is not cleared due to `entrypoint` config.

## Steps to Reproduce (for bugs)
Two files:
```elm
-- src/Main.elm

module Main exposing (..)


import Mod exposing (modFn)

mainFn : Int
mainFn =
    modFn

```

```elm
-- src/Mod.elm

module Mod exposing (..)


modFn : number
modFn = 1

```
elm-tooling.json:
```
{
  "entrypoints": ["./src/Main.elm"]
}
```

1. In `Mod.elm` change name `modFn` -> `modFn1` (in both annotation and impl)
2. You'll see the error in `Main.elm`
3. Change it  back `modFn1` -> `modFn`
4. You'll see the error is still there in `Main.elm`

![image](https://user-images.githubusercontent.com/736697/97788501-32436f00-1bdb-11eb-8812-0696660b4079.png)

Another case: (do after restart server/window)

1. in `Main.elm` `modFn` -> `modFn1`, save, and see the error
2 go to `Mod.elm`: and modify `modFn` -> `modFn1` **only in annotaton**, save
3. You see the error in `Mod.elm` 
4. In `Mod.elm` modify the second `modFn` -> `modFn1`, and save
5. Error is not gone in `Mod.elm`
![image](https://user-images.githubusercontent.com/736697/97788443-c103bc00-1bda-11eb-8ac6-a046aab10b22.png)

## Possible Solution

I tried to follow the logic behind getting and updating diagnostics and seem there are really problems: either DiagnosticProvider 
 need to know if `entrypoint` is used to clear all the errors before updating (as with entry point it should retrun all the errors in project), or `createDiagnostics` should return extended data which includes other modules that have been checked and have no cautions from compiler, so they could be updated.

Also, it probably should still run `elm make` for the current changed file not only for the entry points.

**Comment by Razzeee** [comment]
This should have been fixed with the new version from yesterday.
