### ISSUE TITLE
Output channel name

### ISSUE THREAD

**Issue by whitecolor** [elm-tooling/elm-language-client-vscode#131]
https://github.com/elm-tooling/elm-language-client-vscode/blob/master/client/src/extension.ts#L112

```ts
      const relativeWorkspace = folder.name;
      const outputChannel: OutputChannel = Window.createOutputChannel(
        relativeWorkspace.length > 1 ? `Elm (${relativeWorkspace})` : "Elm",
      );
```

This checks `name.length` probably should check something else (i.e. split by slash parts count) to make a decision about output channel name.

**Comment by Razzeee** [comment]
Have you actually seen this going wrong? I wouldn't expect any slashes to be in there.

The docs of the field we're using says this:
```
        /**
         * The name of this workspace folder. Defaults to
         * the basename of its [uri-path](#Uri.path)
         */
        readonly name: string;
```

**Comment by whitecolor** [comment]
Ok, I just didn't get logic, though there can be multiple outputs for different elm workspaces.

But I don't really get what does this condition `relativeWorkspace.length > 1` mean?

**Comment by Razzeee** [comment]
It's basically there, so that we don't end up with a channel name that has empty brackets like `Elm ()` - not sure if it can actually happen.

**Comment by whitecolor** [comment]
Then it should be at least `relativeWorkspace.length >= 1` ? Though the project should be in dir root for this to happen probably.

**Comment by Razzeee** [comment]
Yeah, sooms right.

**Comment by Razzeee** [comment]
Fixed by https://github.com/elm-tooling/elm-language-client-vscode/commit/4c619ec0dd86df840ec9764785bf70ed052df643
