### ISSUE TITLE
Extension dies with memory access out of bounds

### ISSUE THREAD

**Issue by sporto** [elm-tooling/elm-language-client-vscode#14]
Hi

I have elm-format in my path.

```
~$ elm-format
elm-format 0.8.1
...
```

No matter what I put in settings Elm format won't run on save.

I have tried: Putting the full path e.g. `/usr/local/bin/elm-format`, just `elm-format` and blank. 
It won't format. I cannot see any errors on the VS code output panel. When I use https://marketplace.visualstudio.com/items?itemName=sbrink.elm Elm format runs fine on save.

This is in PopOS which is similar to Ubuntu.

## Update

This happens because the extension dies after a few seconds with `Message: Request textDocument/documentSymbol failed with message: memory access out of bounds`

**Comment by Razzeee** [comment]
Are you on the latest VSCode version? Afaik there have been path changes in the latest release. Still full path should work fine, as that's what I'm using on my dev rig.
https://code.visualstudio.com/updates/v1_36#_launch-terminals-with-clean-environments

**Comment by Razzeee** [comment]
I'm using the `/usr/bin/elm-format` path on manjaro

**Comment by sporto** [comment]
Yes I'm using 1.36.1. Is there maybe anything else I can enable to get more debug information?

**Comment by sporto** [comment]
Hmm, is not just elm-format. Nothing seems to work.
I have installed Node 10.16

I just see this in vs code, definition don't load.

![image](https://user-images.githubusercontent.com/1005498/61683466-ea3b6880-ad58-11e9-90f5-cec59c057320.png)

**Comment by Razzeee** [comment]
There should be an output window labeled "elmLS". That would be interesting. You could also change the verbosity in the settings, but that might be to much info for a start.

**Comment by sporto** [comment]
Ok, that helped a lot

I got the extension starting. This part was a directory ownership problem.
My `elm-stuff` was managed by Docker, so it was under `root`. Changing the owner of that folder got the extension to intialise.

Then it worked for a little bit and the it died with:

```
Message: Request textDocument/documentSymbol failed with message: memory access out of bounds
```

**Comment by Razzeee** [comment]
I'm currently tracking that error down over at the tree-sitter/tree-sitter
repo

**Comment by Razzeee** [comment]
https://github.com/tree-sitter/tree-sitter/issues/394

**Comment by Razzeee** [comment]
This error has been fixed in the master branch of the server, can you test that?
Not sure when I'm able to release it, as I'm hunting some other bugs.

**Comment by sporto** [comment]
Happy to test, but how do I test that? as is a vs code extension.

**Comment by Razzeee** [comment]
https://github.com/elm-tooling/elm-language-client-vscode#contributing--debugging should be enough to get you started.

**Comment by sporto** [comment]
Thanks. 

Upon hitting F5 I get this

```
rejected promise not handled within 1 second: Error: Request initialize failed unexpectedly without providing any details.
extensionHostProcess.js:759
stack trace: Error: Request initialize failed unexpectedly without providing any details.
	at handleResponse (/home/sebastian/Source/other/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:436:48)
	at processMessageQueue (/home/sebastian/Source/other/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:263:17)
	at Immediate.setImmediate (/home/sebastian/Source/other/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:247:13)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)
```

**Comment by Razzeee** [comment]
I'm not sure how that happens, I assume the "Launch Client" config is active in the debug tab?

Anyway I'm preparing a release right now.

**Comment by Razzeee** [comment]
It should be out now.

**Comment by sporto** [comment]
Great thanks. With 0.4.2 elm analyse started working.

Saving and trying to format results in 

```
SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at Interface.errorLinesFromElmMake.on (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/server/out/providers/diagnostics/elmMakeDiagnostics.js:140:46)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
[Info  - 9:10:52 am] Connection to server got closed. Server will restart.
[Error - 9:10:52 am] Request textDocument/formatting failed.
Error: Connection got disposed.
```

**Comment by Razzeee** [comment]
Can you run
`elm make relativePathToFileYouTestedWith --report json --output /dev/null`
and either paste the json or try to validate it on your own?

We found a bug in the 0.19.1 alphas, that errors near anonymous functions (`squares =
  List.map (\n -> n^2) (List.range 1 100)`) were causing broken json. Not sure if that also affects 0.19.0

**Comment by sporto** [comment]
This gives me no output at all. Just success exit code. Is this meant to always produce some json output?

**Comment by Razzeee** [comment]
No, that's what's expected, when there is no error. Are you sure your running this on the file that reported the error in the extension?

**Comment by sporto** [comment]
I'm working on a different computer today and I don't see this issue (I see other slowness issues). The memory issue doesn't happen anymore. So I will close this and open another issue with something more specific.

Thanks
