### ISSUE TITLE
There is no formatter for 'elm' files installed - No Elm workspace contains (file)

### ISSUE THREAD

**Issue by avhubtran** [elm-tooling/elm-language-client-vscode#140]
When I try to format an Elm file with the plugin, it says there's no formatter for elm files.

## Expected Behavior
File should get formatted

## Current Behavior
When formatting an elm file, the following error appears:

![no-elm-formatter](https://user-images.githubusercontent.com/69667324/100920465-047a7000-3490-11eb-8274-186bd04be806.png)

## Steps to Reproduce (for bugs)
1. Install Elm plugin v1.5.3
2. Set "Elm LS: Elm Format Path" setting to the path to elm-format (installed locally with npm)
3. Open a folder that contains multiple subfolders each having an elm-package.json
3. Open an Elm file in each of the subfolders/src
3. make some whitespace modifications to the file
3. save the file
4. Cmd-Shift-P  ->  ">Format Document"

(note: if I do the same but don't save the file before "Format Document", then I don't get the popup, but the file still does not get formatted)

## Context
My team has to manually run formatting scripts before committing.

## Your Environment

* Version used: 1.5.3
* Editor name and version (e.g. VSCode 1.36.1): 1.51.1
* Environment name and version (e.g. node.js 5.4): 12.14.1
* Operating System and version: Linux / Ubuntu 20.10

**Comment by Razzeee** [comment]
Did you try without setting the path to elm-format manually?

**Comment by avhubtran** [comment]
Same thing happens when the elm-format path is not set.

And side-note: elm-format is at `/<path to project>/client/elm/node_modules/.bin/elm-format`

**Comment by Razzeee** [comment]
It does work for me with manjaro when I either do complete path

`/home/razze/development/elm-chorus/node_modules/.bin/elm-format`
or
`./node_modules/.bin/elm-format`

not sure if your sub folders can affect this

**Comment by avhubtran** [comment]
is there any debug log I can look at?

**Comment by Razzeee** [comment]
F1 > "Output: Focus on output view" > drop down on the right, select the one starting with "Elm"

**Comment by Razzeee** [comment]
For me a wrong format path seems to crash the server, so we defiantly need to look at that (might be master)

**Comment by avhubtran** [comment]
ah:
```
[Error - 2:36:36 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: No Elm workspace contains /...(path to project).../client/elm/...(folder).../src/...(path to elm file)....elm
  Code: -32603 
```

**Comment by avhubtran** [comment]
there are multiple elm folders in the project, and it looks like it's only finding the elm.json from one of them.  (and actually most of them are Elm 0.18)

**Comment by Razzeee** [comment]
I think we only take the top most elm.json per folder. See for e.g. https://github.com/elm-tooling/elm-language-client-vscode/issues/94

**Comment by Razzeee** [comment]
Closing, as it should be tracked in the other issue.
