### ISSUE TITLE
Implement a test runner

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-client-vscode#147]
We could do something like https://github.com/microsoft/vscode-java-test to be able to run tests through the UI.

**Comment by Razzeee** [comment]
For reference, this seems similar https://github.com/formulahendry/vscode-dotnet-test-explorer

**Comment by Razzeee** [comment]
https://github.com/microsoft/vscode/issues/107467

**Comment by Razzeee** [comment]
We should spend some time with https://github.com/frawa/vscode-elm-test-runner and consider recommending it/integrating it.

**Comment by Razzeee** [comment]
The basics for this are already merged
