### ISSUE TITLE
Couldn't start client Elm

### ISSUE THREAD

**Issue by JohnDowson** [elm-tooling/elm-language-client-vscode#148]
## Expected Behaviour
LSP starts, provides linting and autocompletion.

## Current Behaviour
![Error popups](https://i.imgur.com/hAUyHtT.png)

## Steps to Reproduce (for bugs)
1.  Create a folder and open it in VSCode
2. `elm init` in that folder
3. Create and open a .elm file in the ./src folder

Installing elm-tooling and using it to generate an elm-tooling.json doesn't change anything.  
Specifying full path to elm executable doesn't affect the behaviour.

## Your Environment
* Extension version 1.5.3
* VSCode v1.52.1
* node.js 12.14.1
* Windows 10 1809

**Comment by JohnDowson** [comment]
Well, never fucking mind, it was because my project folder was named elm-stuff and apparently naming your project that breaks the extension for some reason.

**Comment by Razzeee** [comment]
Yes, we don't look for `elm.json` in folders that include `elm-stuff` or `node_modules` for performance reasons.
