### ISSUE TITLE
Parsing error while code compiles

### ISSUE THREAD

**Issue by Yagger** [elm-tooling/elm-language-client-vscode#154]
Elm code does compile, but still in VSCode all my code is red and error says "Parsing error Elm [1, 1]".
If I make an error in code and make compiler fail, then VSCode shows correct errors. Once I fix it and save, all lines become red again, without explaining what's going on.

<img width="1440" alt="Screenshot 2021-01-20 at 17 33 39" src="https://user-images.githubusercontent.com/1056226/105198173-0da9c400-5b46-11eb-8322-b2975cbab19f.png">

## Expected Behavior
If compiler compiles, there should be no red markers in VSCode.
If there are red markers in VSCode, it should give helpful message.

## Current Behavior
If compiler compiles, VSCode Elm plugin may still show red markers.
Message is just "Parsing error", which is not helpful.

## Steps to Reproduce (for bugs)
I am not sure how to reproduce it. Other projects are working fine, at the moment I only have this problem with particular project.
[ui.zip](https://github.com/elm-tooling/elm-language-client-vscode/files/5843568/ui.zip)

## Your Environment
VSCode 1.52.1 
node.js 14.15.3
npm 6.14.11
MacOS Big Sur 11.1

**Comment by Razzeee** [comment]
Running elm-format on your project get's rid of all the problems for me. Probably the same line comments, that fool the parser.

**Comment by Yagger** [comment]
@Razzeee thanks! elm-format does the trick.
