### ISSUE TITLE
Definitions/references should work in non-writable modules

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-client-vscode#168]
It can be really helpful to follow code back to the sources even when going through non-writable modules. We should allow this.

**Comment by jmbockhorst** [comment]
It actually happens here: https://github.com/elm-tooling/elm-language-client-vscode/blob/2a250cb5661fb78c71d01628fac8a80b7949ce8a/client/src/extension.ts#L154

**Comment by Razzeee** [comment]
Just removing that line seems like it works. But also shows some problems, when Kernel modules are loaded. There might be more problems, but I only tested the spa-example, which only has:
 "NoRedInk/elm-json-decode-pipeline": "1.0.0",
 "rtfeldman/elm-iso8601-date-strings": "1.1.0"
that don't rely on kernel code

**Comment by jmbockhorst** [comment]
Fixed in https://github.com/elm-tooling/elm-language-client-vscode/commit/ee4eea363f85fb9ecbca4a44a07f57963114dc3f.
