### ISSUE TITLE
Allow disabling "exposed" and "references"

### ISSUE THREAD

**Issue by bbugh** [elm-tooling/elm-language-client-vscode#17]
Great work here! Seems like the language server already has a lot of great coverage.

This feature that shows the exposed/local and the number of references is useful in some cases, but the way it's implemented is disruptive to my workflow. I've tried to push through but writing code while the editor lines are moving around is too jarring to use. It's especially bad when writing function type definitions and bodies. 

<img width="155" alt="image" src="https://user-images.githubusercontent.com/438465/62303236-614fbb80-b441-11e9-9bd6-45c8dd210254.png">

## Expected Behavior
The feature can be toggled on and off. 😍

## Current Behavior
The feature is always on. 😰

## Possible Solution
Preferably, the feature is 1) togglable via the command palette and 2) has a default setting that allows us to keep it off until desired.

## Your Environment
* Version used: 0.4.2

**Comment by mewhit** [comment]
Or only  display on select, like git lens.

**Comment by Razzeee** [comment]
@mewhit the client should decide how to show it. afaik editors like vim so show code lenses in the same line for e.g.

**Comment by Razzeee** [comment]
>You can enable or disable code lense by setting the editor.codeLens setting in user settings (see https://code.visualstudio.com/Docs/editor/editingevolved#_reference-information for more info).

So we should not build a custom handling.
