### ISSUE TITLE
interactive key word fails to render multiple graphs

### ISSUE THREAD

**Issue by yean8mun** [elm-tooling/elm-language-client-vscode#173]
I have elm codes running in VSCode installed with elm tools extension version `v2.0.3`
The `interactive` keyword fails to render anything on the multiple graphs.

## Expected Behavior
I expect the graphs to be shown with tooltip interaction feature on the points.
![image](https://user-images.githubusercontent.com/61852565/111914874-c4092700-8a6b-11eb-9207-80f4b4d6f1ae.png)

## Current Behavior
The graphs are not shown. Only the axes are visible.
![Screenshot 2021-03-21 at 17 31 18](https://user-images.githubusercontent.com/61852565/111914791-6ecd1580-8a6b-11eb-9b8c-b2a5118c1bca.png)

## Possible Solution
Is there anything wrong in my elm codes below? Or the `interactive` keyword does not like my CSV file as attached?

## Steps to Reproduce (for bugs)
```
```elm {v interactive}
statsCorrelation : Spec
statsCorrelation =
     let
        corrData2 =
            dataFromUrl "./correlation_simple.csv" []
        enc =
             encoding
                 << position X
                 [ pRepeat arColumn
                 , pQuant
                 , pScale [ scZero False ]
                 ]
                 << position Y
                 [ pRepeat arRow
                 , pQuant
                 , pScale [ scZero False ]
                 ]
                 << tooltip [ tName "view_count", tQuant ]
     in
     toVegaLite
     [ corrData2
     , repeat
         [ rowFields [ "view_count", "likes", "dislikes", "comment_count" ]
         , columnFields [ "view_count", "likes", "dislikes", "comment_count"]
         ]
     , specification ( asSpec [ circle [], enc [] ])
     ]```
```

1. Paste the code above to VSCode installed with elm tools. Save as a markdown file. Do not forget to save the CSV file here: [https://yean8mun.github.io/DataViz/correlation_simple.csv](https://yean8mun.github.io/DataViz/correlation_simple.csv)
2. Install `Markdown Preview Enhanced with litvis` extension in VSCode
3. Preview the markdown. Observe no points shown at the graphs. Refer to the image at the Current Behavior
4. Remove the `interactive` keyword at ````elm {v interactive}` & everything works like below
![Screenshot 2021-03-21 at 17 36 42](https://user-images.githubusercontent.com/61852565/111914969-13e7ee00-8a6c-11eb-8403-d4bff21127be.png)

## Context
I want to show do some simple interactive work with multiple graphs like showing tooltip. How do I make it work in elm?

## Your Environment
* Version used: v2.0.3
* Editor name and version (e.g. VSCode 1.36.1):  February 2021 version 1.54
* Environment name and version (e.g. node.js 5.4): node.js version 6.14.10
* Operating System and version: MacOS version 10.14.6

**Comment by Razzeee** [comment]
I don't think that has anything to do with our extension, I think you need to report this over at https://github.com/gicentre/vscode-markdown-preview-enhanced-with-litvis/issues
