### ISSUE TITLE
Link in documentation leads to 404 page

### ISSUE THREAD

**Issue by aparent-emgs** [elm-tooling/elm-language-client-vscode#174]
This link in the documentation leads to a 404 page at the moment:
![image](https://user-images.githubusercontent.com/19916166/112357308-c5be2f00-8ca5-11eb-93b6-63fbe353f29a.png)
![image](https://user-images.githubusercontent.com/19916166/112358079-601e7280-8ca6-11eb-9d77-8f82b1f859c2.png)

## Expected Behavior
Link should lead to an available and relevant resource.

## Current Behavior
Link leads to a 404 error page.

## Your Environment
* Version used: v2.1.0
* Editor name and version: Visual Studio Code 1.54.3
* Operating System and version: Windows x64 10.0.19042

**Comment by Razzeee** [comment]
Great catch
