### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rumothy** [elm-tooling/elm-language-client-vscode#175]
- Issue Type: `Performance`
- Extension Name: `elm-ls-vscode`
- Extension Version: `2.0.3`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\rumot\AppData\Local\Temp\elmTooling.elm-ls-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Razzeee** [comment]
Please test the current version of the extension
