### ISSUE TITLE
Disable False Error Squiggles. Please!

### ISSUE THREAD

**Issue by madasebrof** [elm-tooling/elm-language-client-vscode#192]
## Expected Behavior

Only check for parse errors on a file save, NOT as you are typing!

## Current Behavior

<img width="452" alt="Screen Shot 2021-05-26 at 4 15 11 PM" src="https://user-images.githubusercontent.com/1993403/119729762-0885ba00-be43-11eb-8b13-1ab4d8071b06.png">

Right now, the linter is try to parse as you type. Which sounds super cool, and I'm sure was hard to make work well, but is super mentally taxing. For example, if I type the code:

```
type alias Foo =
```

as I'm typing, that will all show up underlined in horrible red squiggles, indicating I am doing something terribly wrong, when in fact I am writing perfectly valid Elm code. I just haven't finished my thought yet.

As I keep typing, the errors will keep flashing on and off, depending on where I am, e.g. 
```
type alias Foo =
    {}
```
is valid, but 
```
type alias Foo =
    { baz
    }
```
is not.

## Possible Solution

Only enable this kind of pedantic linting on save, then disable as soon as someone starts typing anything! This, to me, is a much more productive and generally best-practices approach to coding.

> Premature linting is the root of all evil. - Donald Knuth

Or, at a minimum, add a setting to disable code linting. 

PS The compiler will point out any errors!

:)

## Context

Daily coding, moving over from Atom.

PPS I posted about this on Elm Discourse. Maybe someone will reply with a solution...
PPPS Thanks for writing the language server for Elm!!!

**Comment by madasebrof** [comment]
Okay, I found the option after looking at the Elm language Server. 

😄 

Just in case someone else stumbles across this, to find, do a search for `elmLS` in Settings, the check:

**Elm LS: Only Update Diagnostics on Save**

```
"elmLS.onlyUpdateDiagnosticsOnSave": true
```

Yay!

I'll leave this here just in case y'all decide to make this the default behavior (which I'd recommend).

Thanks again!

**Comment by Razzeee** [comment]
I don't think that's the way to go. We can probably make it less distracting by adding a bit more debouncing, but early and good feedback (yes, we can improve here) is better then late or well no feedback. Especially for newcomers or people that come from more developed tool ecosystems.

Your design (which we had to do before we could parse like this) lead to people having to constantly save, just to get help.

That being said, I can see, how this can be distracting to people that are more advanced and know what they are doing, but I would just suggest to setup your environment to run linting on save then.
