### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jmbaa** [elm-tooling/elm-language-client-vscode#204]
- Issue Type: `Performance`
- Extension Name: `elm-ls-vscode`
- Extension Version: `2.2.0`
- OS Version: `Linux x64 5.4.0-80-generic`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/elmTooling.elm-ls-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Razzeee** [comment]
Missing the cpuprofile. Closing.
