### ISSUE TITLE
Missing syntax highlighting

### ISSUE THREAD

**Issue by step4** [elm-tooling/elm-language-client-vscode#211]
## Expected Behavior
Types are getting highlighted like you can see here in this video at time 18:18
[Building UIs in the Dark (aka Elm Programming)](https://youtu.be/sKxEwjKQ5zg?t=1098)

## Current Behavior
In my case Types are not getting highlighted
![image](https://user-images.githubusercontent.com/11348121/132990055-9a892116-8429-448b-8512-24a521dc6a69.png)

I'm running a Windows 11 preview build. But I can't imagine that is the cause.

## Steps to Reproduce
1. Install VSCode
2. Install elm-tooling extension

## Your Environment
* Version used: 2.2.1
* Editor name and version (e.g. VSCode 1.36.1): 1.60.0
* Environment name and version (e.g. node.js 5.4):
* Operating System and version: Windows 11 21H2

**Comment by razzeee** [comment]
This depends on your color theme in vscode and if it supports the tokens.
So you might have to patch that theme or use another one.

![image](https://user-images.githubusercontent.com/5943908/132991401-e8a5d7a0-4793-4c30-9bcc-883a3aff1fb9.png)

**Comment by step4** [comment]
Oh thanks for that information.
Bummer that only one preinstalled theme works with these tokens.

I will go now an look for nice themes :-)

**Comment by razzeee** [comment]
Yeah, it is, maybe we're doing something wrong. But I only inherited that
code, so I'm not sure.

Christian Rausch ***@***.***> schrieb am So., 12. Sept. 2021,
16:33:
