### ISSUE TITLE
Formatting doesn't seem to do anything

### ISSUE THREAD

**Issue by allanderek** [elm-tooling/elm-language-client-vscode#22]
I wouldn't be surprised if this is some configuration setting that I've not set or something rather than a more general bug. However the Elm-discourse somehow didn't seem to be the appropriate place for this.

## Expected Behavior

Upon saving the a file, or running the format document command I would expect to see the document formatted by elm-format.

## Current Behavior

However it doesn't seem to have that effect. In particular the order of imports remains unchanged even though they are out-of-elm-format-order. It isn't adding new lines where I expect, etc. Generally the document appears completely unchanged.

The first time I noticed this I explicitly ran the "Format Document" command and it complained that I had multiple formatters associated with Elm files and asked me to choose, but the two options it gave me were identical "elmTooling.elm-ls-vscode". 

## Steps to Reproduce (for bugs)

I'm not sure how you would reproduce this if it is working for you. The output tab for the project does not mention formatting at all. The only vaguely bad seeming lines in the output appear to have nothing to do with formatting:

```
(node:4629) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:4629) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:4629) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
```

Here are my settings:

```
{
    "elmLS.elmPath": "/home/allanderek/.npm-global/bin/elm",
    "elmLS.elmFormatPath": "/home/allanderek/.npm-global/bin/elm-format",
    "editor.formatOnSave": true,
    "window.zoomLevel": 0,
    "editor.acceptSuggestionOnEnter": "off",
    "[elm]": {
        "editor.defaultFormatter": "elmTooling.elm-ls-vscode"
    }
}
```

I've put the explicit paths to the elm executables in case that was to blame but didn't change anything.

**Comment by Razzeee** [comment]
Which version of elm-format the new 0.8.2 release?

**Comment by allanderek** [comment]
Yes, 0.8.2

**Comment by Razzeee** [comment]
And there is nothing about timeouts in your logfile? I'm not 100% sure if they would be in the language server logfile or in a vscode related one. But there have been reports. There also is the suggestion to increase that timeout.

https://github.com/elm-tooling/vscode-elm#formatting-with-elm-format

**Comment by allanderek** [comment]
There was nothing about timeouts in the logfile.
However, setting the timeout to 1500 as suggested fixed it for me.
Thank you!

This issue is therefore closed for *me*, but I don't know if you would rather keep it open to track a more general fix or documentation for it.

**Comment by Razzeee** [comment]
Are you using windows or does this happen on another platform for you?

**Comment by allanderek** [comment]
Oh I meant to put that on the original bug report.
I'm on Manjaro Linux.

**Comment by Razzeee** [comment]
Your issue is solved right?
Should we test again with the defaults and see if it improved?

**Comment by allanderek** [comment]
It seems working for me now yes.
