### ISSUE TITLE
Language server fails to start with error "unregistered dependency token"

### ISSUE THREAD

**Issue by N-Onorato** [elm-tooling/elm-language-client-vscode#234]
Howdy, I'm new to Elm and while trying to get setup ran into some problems. Hopefully this is an obvious user error, but if not may be a bug.

## Expected Behavior
When opening a folder containing a valid Elm project in VSCode we expect the language server to start and for its functions to work.

## Current Behavior
When opening a folder containing a valid Elm project (from Elm init) VSCode raises 3 error notifications.
<img width="353" alt="image" src="https://user-images.githubusercontent.com/13564856/158712458-4a6e1adb-77cb-4b39-98c4-8e94159a63d9.png">

Elm output shows the following logs
```
[Info  - 9:52:55 PM] Loading Elm tree-sitter syntax from ..\..\..\.vscode\extensions\elmtooling.elm-ls-vscode-2.4.0\server\out\tree-sitter-elm.wasm
[Info  - 9:52:56 PM] No elm.json found
[Error - 9:52:56 PM] Server initialization failed.
  Message: Request initialize failed with message: Attempted to resolve unregistered dependency token: "ElmWorkspaces"
  Code: -32603 
[Error - 9:52:56 PM] Starting client failed
  Message: Request initialize failed with message: Attempted to resolve unregistered dependency token: "ElmWorkspaces"
  Code: -32603 
```

## Steps to Reproduce (for bugs)
This bug may not be reproducible. But for me...

1. Open either a personal project or the elm-spa-example project with vscode.
2. Observe vscode display the three error notifications shown above.

## Context
*I have not had this working before*, I'm new to elm and was trying to get setup when I ran into this issue.

## Your Environment

* Elm Extension: 2.4.1 (also appears on 2.4.0)
* Windows 11: Version 10.0.22000 Build 22000
* VSCode: 1.65.2
* Elm: 0.19.1 (Installed with windows package manager, available in PATH)
* Node: v16.14.0

**Comment by razzeee** [comment]
Did you do https://github.com/elm-tooling/elm-language-client-vscode#install

Or did you install those diffrently?

**Comment by Eptis** [comment]
Maybe relevant information, but the extension has worked for me for the past year, until I updated to the latest VSCode version this morning.

![image](https://user-images.githubusercontent.com/88688/158805622-6f48321e-385c-4866-89a3-adcba0eccb66.png)

**Comment by N-Onorato** [comment]
> Did you do https://github.com/elm-tooling/elm-language-client-vscode#install
> 
> Or did you install those diffrently?

Yes, I followed those install directions. VSCode, Node, and elm we're already installed using windows package manager. I did run `npm install -g elm-test elm-format` after installing the extension. I thought the order might matter and tried reinstalling the extension through the VSCode UI, but that hasn't made a difference.

**Comment by N-Onorato** [comment]
I cloned the repo and started the debuggers, here's a stack trace...
```
stack trace: Error: Request initialize failed with message: Attempted to resolve unregistered dependency token: "ElmWorkspaces"
	at handleResponse ([c:\Users\N_ono\repos\elm-language-client-vscode\client\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48]())
	at processMessageQueue ([c:\Users\N_ono\repos\elm-language-client-vscode\client\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17]())
	at Immediate.<anonymous> ([c:\Users\N_ono\repos\elm-language-client-vscode\client\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13]())
	at processImmediate (internal/timers.js:461:21)
	at process.callbackTrampoline (internal/async_hooks.js:131:14)
```

**Comment by razzeee** [comment]
I think the trouble starts with not being able to find the elm.json. You end up here, https://github.com/elm-tooling/elm-language-server/blob/b22398b3398b20640cbdd9cc6d6b70a14826b800/src/server.ts#L107, you might want to try to remove `elm-stuff` and rerun `elm init` maybe even`elm install` (even if that errors without params, it still downloads stuff in the background)

**Comment by N-Onorato** [comment]
The issue has been discovered! It's all due to terrible coincidence. In organizing my code, I decided to explore elm under the `elm-stuff` directory. By chance it seems that's also the name of the directory elm or the plugin creates in a project.

I don't know if this is an issue worth fixing then. But the issue is that a project under an `elm-stuff` directory breaks the plugin. E.g. `elm-stuff/my_project`

**Comment by razzeee** [comment]
Yeah, we deliberatly don't index anything in `elm-stuff` or `node_modules` folders
