### ISSUE TITLE
ENOENT: no such file or directory tree-sitter-elm.wasm

### ISSUE THREAD

**Issue by sporto** [elm-tooling/elm-language-client-vscode#26]
While trying why this is not working. I cloned the repo as per the instructions in the readme and started debugging the extension. Then opened my source code and got this error, see below.

## Current Behavior

When the extension tries to initialise I see this.

```
rejected promise not handled within 1 second: Error: Request initialize failed with message: ENOENT: no such file or directory, open '../../other/elm-language-client-vscode/server/out/tree-sitter-elm.wasm'
extensionHostProcess.js:775
stack trace: Error: Request initialize failed with message: ENOENT: no such file or directory, open '../../other/elm-language-client-vscode/server/out/tree-sitter-elm.wasm'
	at handleResponse (/home/sebastian/Source/other/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:436:48)
	at processMessageQueue (/home/sebastian/Source/other/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:263:17)
	at Immediate.setImmediate (/home/sebastian/Source/other/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:247:13)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)
```

## Possible Solution

I did `cd server && npm run copy-wasm` and the extension started working.
This probably needs to be somewhere in the extension installation code.

## Steps to Reproduce (for bugs)

- Clone this repo
- F5
- Open Elm source code

## Your Environment
* Version used: 0.5
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.37.1
* Environment name and version (e.g. node.js 5.4): Node 10.16.3
* Operating System and version: PopOS 19.04

**Comment by Razzeee** [comment]
Unfortunately the development build that your building in this case is fairly different from the one we push to vscode. So this might fix your local compile but probably for other reasons.

I pushed an update, that should address the problem in https://github.com/elm-tooling/elm-language-client-vscode/issues/27 that I think caused this.

**Comment by Razzeee** [comment]
This was due to an oversight on how to setup a local dev environment. Should be fixed by https://github.com/elm-tooling/elm-language-client-vscode/commit/09f6e49a2244f7ca9ae31072cd3e38210e2ab208
