### ISSUE TITLE
Cannot find module 'request'.

### ISSUE THREAD

**Issue by simerlec** [elm-tooling/elm-language-client-vscode#27]
Update to 0.5.0 broke this extension for me. It simply won't load and I found the following error in the VSCode developer tools:

<img width="1317" alt="elmls-error" src="https://user-images.githubusercontent.com/5793380/63769070-228f1300-c8d2-11e9-8271-3ba54aa92232.png">

I also tried re-installing the extension as well as removing it completely from the .extensions folder of VSCode and re-installing afterwards.

Thanks for your help 👍 

## Expected Behavior
The VSCode extension should load.

## Current Behavior
The extension won't load and with the error provided above.

## Your Environment

* Version used: 0.5.0
* Editor name and version (e.g. VSCode 1.36.1): 
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
* Environment name and version (e.g. node.js 5.4): Node v12.3.1
* Operating System and version: MacOS Mojave 10.14.6 (18G87)

**Comment by Razzeee** [comment]
Just pushed a release, should be available in some minutes and hopefully fix this.

**Comment by Razzeee** [comment]
Should be fixed by https://github.com/elm-tooling/elm-language-client-vscode/commit/182401a51c2d8aa06385a135d60daa73127fbea0
