### ISSUE TITLE
Specify what license the plugin is released under.

### ISSUE THREAD

**Issue by DamianReeves** [elm-tooling/elm-language-client-vscode#29]
## Expected Behavior
Please add a license to the project i.e. through a License.md file.

## Current Behavior
No license is specified so usage in some settings will be restricted.

## Possible Solution
Provide a License.md file.

## Steps to Reproduce (for bugs)
N/A

## Context
I want to bring this extension into the company I work for, for internal use but Open Source software must be one of the allowed licenses to bring it in.

**Comment by Razzeee** [comment]
Yeah, it should probably be a bit more prominent. https://github.com/elm-tooling/elm-language-client-vscode/blob/master/package.json#L8

**Comment by Razzeee** [comment]
Added https://github.com/elm-tooling/elm-language-client-vscode/blob/master/LICENSE

**Comment by DamianReeves** [comment]
Thanks for this.
