### ISSUE TITLE
"Initializing workspace: Indexing" uses all avaliable memory and eventually crashes

### ISSUE THREAD

**Issue by ingLomeland** [elm-tooling/elm-language-client-vscode#390]
After the new 2.5.0 I can no longer use the extention. On indexing it uses all memory and eventually crashes. If I look at the output I see that it creates x amount of sessions which is probably why it uses so much memory. 
<img width="204" alt="image" src="https://user-images.githubusercontent.com/87584165/193553715-26700fd4-a275-4993-9803-05c9c9399a3f.png">

## Expected Behavior

It should only start 1 session of the indexing

## Steps to Reproduce (for bugs)

1. Upgrade to the latest version of the plugin
2. Start a docker container with node 14 and connect vscode to the container
3. Open the folder with the elm project so that it starts indexing

## Your Environment

* Version used: 2.5.0
* Editor name and version (e.g. VSCode 1.36.1):  1.71.2
* Environment name and version (e.g. node.js 5.4): 14
* Operating System and version: Ubuntu 22.04

**Comment by razzeee** [comment]
I can't repro this. 

I've added a devcontainer to https://github.com/rtfeldman/elm-spa-example but I only ever get one instance that way. Even when changing between node 14 / 16.

**Comment by lawik** [comment]
We've seen sudden crashes on one Windows + WSL setup and one MacBook Pro (M1).
This seems to have been after a VS Code update. Whether it was triggered by updating the extension or VS Code is a bit unclear.

**Comment by rupertlssmith** [comment]
You can rollback to an older version with File -> Preferences -> Extentions, then on the Elm extension use the settings icon and Install Another Version. 

I went back one to 2.4.1
2.5.0 was launching lots of processes and running very slowly.

**Comment by escherlies** [comment]
I needed to roll back to 2.4.1 as well. 2.5.0 crashed on my ~25k LOC project after making some changes. (M1 Mac)

Happy to help with more info if someone can tell me how to set some debug flags for this extension.

**Comment by razzeee** [comment]
This is the only change that could cause the multiple clients, as the vscode client decides when/if to start a server https://github.com/elm-tooling/elm-language-client-vscode/commit/96cf21bc84a2fe4450981b0fb9b301f92d9b038a

**Comment by razzeee** [comment]
Can somebody try https://github.com/elm-tooling/elm-language-client-vscode/pull/391 ?

It's just a basic cleanup, I don't expect it to fix it, but maybe it does? As I'm not getting the problem, it's hard to say.

**Comment by harmboschloo** [comment]
It seems it starts a client for every elm.json in the project. We have 5 elm.json files in our project and I get 5 clients.

I also get 5 of these:

![image](https://user-images.githubusercontent.com/7893506/193758328-d52a3a0a-7571-4128-9dae-1448285cdef3.png)

Interestingly for quick fixes I get even more...

![image](https://user-images.githubusercontent.com/7893506/193758683-a056b1bb-c4e4-4fb8-8fa3-7f28e7f26ced.png)


If I load a project with only one elm.json every works as expected.

I don't get a crash personally but it is using a lot of resources.

**Comment by razzeee** [comment]
Yeah, found the problem due to somebody from the elm slack sharing their OSS project, that had this problem too.

Expect a fix soonish.

**Comment by harmboschloo** [comment]
Thanks for the 2.5.1 fix. That solved the duplicate clients. But now for me the client crashes every minute or so.

I've also tested this with https://github.com/rtfeldman/elm-spa-example  and I can easily reproduce it by doing the following:
- open any elm file
- on an empty line press enter (insert a new line), then ctrl+s to save
- repeat the previous step

If you repeat step 2 quick enough the client will stop responding after a couple of times. The last output message is always `Changed text document, going to parse it.`. The only way to recover is to close vscode and open it again.

I've had this problem as well with the 2.4 version, but then it happened a couple of times per week. Now it's every minute or so (I guess I hit ctrl+s a lot...)

**Comment by razzeee** [comment]
I did it 50x in `CommentId.elm` and it doesn't seem to happen. Maybe there's something more involved, can you make sure it happens in that file too? And it might be OSS related? Node version etc?

I've tested on linux with node 16.10.0

**Comment by harmboschloo** [comment]
Yes I also get it with `CommentId.elm`. I usually need less then 5 times. I'm guessing then it only happens on  Windows.

- Windows 11 Home
- Node v16.16.0

**Comment by pfiadDi** [comment]
Also had various troubles on my Mac M1 everything slowed down or didn't work. So I switched back to 2.4.1

**Comment by gouvermxt** [comment]
It's crashing for me as well on an Intel MacBook Pro.

**Comment by razzeee** [comment]
It should hopefully now work with 2.5.2

**Comment by harmboschloo** [comment]
2.5.2 works well for me again. Thanks!
