### ISSUE TITLE
Underline bad imports

### ISSUE THREAD

**Issue by lydell** [elm-tooling/elm-language-client-vscode#41]
## Expected Behavior
`import Foo` is underlined with red if it does not exist.

## Current Behavior
`module` is underlined with red.

## Steps to Reproduce (for bugs)

```elm
module Main exposing (..)

import Math


result =
    Math.add 1 2
```

Since we haven’t made `Math.elm` yet, Elm gives us an error ("UNKNOWN IMPORT - The Main module has a bad import"). That message is shown by hovering the `module` keyword, which is underlined with red. Shouldn’t `import Math` be underlined instead?

## Context
I understand what the error is faster when the code that causes the error is pointed out.

## Your Environment

- Version used: 0.6.0
- Editor name and version: VSCode 1.39.2
- Environment name and version: Node.js v12.8.0
- Operating System and version: macOS Mojave

**Comment by Razzeee** [comment]
I agree. Unfortunately the current elm compiler only returns the string and not the location.

```
UNKNOWN IMPORT - The Huffman module has a bad import:

    import Foo

I cannot find that module! Is there a typo in the module name?

When creating a package, all modules must live in the src/ directory.
```

Can you take this too https://github.com/elm/error-message-catalog ?

**Comment by lydell** [comment]
Sure! https://github.com/elm/error-message-catalog/issues/310

**Comment by Razzeee** [comment]
Going to close this, as there is no work for us to do on this.
