### ISSUE TITLE
Can we improve "marketing"?

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-client-vscode#5]
Most people will install the plugin with vscode. Chances are high they know little about elm, the community and the tooling. They probably don't know and don't need to know the language server protocol. So looking at the current e try I'm asking myself if we can have a name, title and description that is less confusing but makes clear this plugin can do stuff the previous plugins can't do.

![Screenshot_20190626-133314~2](https://user-images.githubusercontent.com/13085980/60177180-8173d580-9818-11e9-950c-a948faf8cde7.png)

**Comment by andys8** [comment]
Even a special logo for `elm-tooling` would be nice :)

**Comment by Razzeee** [comment]
Agreed, but not having many ideas and am not a graphics guy.

**Comment by Razzeee** [comment]
`Elm Bot` - your elm programming buddy

**Comment by andys8** [comment]
> `Elm Bot` - your elm programming buddy

That's too much :D

**Comment by andys8** [comment]
Logo: A wrench ("tool") made out of elm-like triangles maybe? :)

**Comment by Razzeee** [comment]
Cool idea, but what about a robot? :D

**Comment by andys8** [comment]
Namespace conflict with a chatbot project I'm working on :D

**Comment by Razzeee** [comment]
lol

btw I think I've already seen a wrench in elm optic somewhere?

**Comment by andys8** [comment]
Oh no.

Hmm, I came up with this very bad first attempt. Now you or somebody else has to replace it with a better logo :)

![image](https://user-images.githubusercontent.com/13085980/60216856-7a29e780-986b-11e9-94ec-d54392443e89.png)

**Comment by vork** [comment]
I have a simple idea:

Else -
Elm Language Server Extended 
Or:
Elm Language SErver

Potential logo ideas based on a typical flow diagram. But more abstract, modern and in sync with the Elm Logo Style.

**Comment by Razzeee** [comment]
Updated the org icon to 
![wrench-tangram](https://user-images.githubusercontent.com/5943908/63003434-674d8f80-be78-11e9-97ba-4cd33c47ab6e.png)

**Comment by Razzeee** [comment]
Closing this as we have a new icon
