### ISSUE TITLE
Refactor::extract to function

### ISSUE THREAD

**Issue by AllNamesRTaken** [elm-tooling/elm-language-client-vscode#50]
As the code grows I want to easily extract functions to limit clutter and increase reuse.

## Expected Behavior
Suggestion: As you right click on selected code choose Refactor... you get a choice to "extract to function". Clicking this should break that code out into a separate function in a let statement. There could also be more choices such as "extract to let statement" and "extract to function" which would declare it in the same file but outside of current function.

## Current Behavior
Currently there is no refactor behavior to my knowledge.

## Context
I tend to write code in one block and refactor often as it grows in other languages. This way of working has an extra cost in Elm which could be removed.

## Your Environment
Elm 0.19.0
Windows 10
VSCode 1.39.2
Elm 0.7.2 plugin
node: 12.0.0

**Comment by AllNamesRTaken** [comment]
With some assistance I would be willing to give it a go. I have no clue how it runs but I am an experienced TS dev.

**Comment by Razzeee** [comment]
I checked some other language servers to see if any one already supports it. This seems like an implementation. But I haven't tested it yet. https://github.com/theia-ide/typescript-language-server/blob/101dae4f7b598e9bafcaa8c316f21e57341e6350/server/src/refactor.ts#L47

**Comment by AllNamesRTaken** [comment]
How is the debuggability of this?
I feel like just reading that code doesn't tell me if this would work or not.

**Comment by Razzeee** [comment]
Not sure about the other project I linked above. But if your using vscode to compile this as outlined in https://github.com/elm-tooling/elm-language-client-vscode#contributing--debugging

Then you should get multiple configs in the debug view. Normally you want to start the client. 

But if you want to debug something on the server:
1. Start the client
2. Open an elm project and an elm file
3. Goto the debug tab in the vscode instance where your editing from
4. Choose the first config with the 6010 port mentioned
5. Start that config

That will attach a debugger and you should be able to set breakpoints everywhere.

**Comment by Razzeee** [comment]
We now have extract to (new) function and extract to an existing let.
So I guess we would be missing extract to a new let? I'm closing it for now, feel free to reopen, if you think that usecase is important.

CC @jmbockhorst

**Comment by jmbockhorst** [comment]
I didn't implement "extract to new let" because how to we decide where to put the new let? Seems like that could get complicated.
