### ISSUE TITLE
Syntax highlighting of expressions beginning with "import"

### ISSUE THREAD

**Issue by SiriusStarr** [elm-tooling/elm-language-client-vscode#54]
This may be currently unsolvable due to the TextMate grammar limitation, but function names that begin with "import" are erroneously highlighted as `import` statements (with the rest of the label unhighlighted).  This additionally breaks highlighting of the type annotation.

![2019-11-10_14-34](https://user-images.githubusercontent.com/2049163/68552007-2e657e00-03c7-11ea-95e3-4418d7dc8489.png)

**Comment by Razzeee** [comment]
Fixed in https://github.com/elm-tooling/elm-language-client-vscode/commit/28788e723c0c289fdc49e745771977c0f798ca0a
