### ISSUE TITLE
Migrate to the native testing API

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-client-vscode#571]
https://github.com/microsoft/vscode-docs/blob/vnext/api/extension-guides/testing.md#migrating-from-the-test-explorer-ui

**Comment by razzeee** [comment]
Duplicate of https://github.com/elm-tooling/elm-language-client-vscode/issues/185

**Comment by jmbockhorst** [comment]
My bad. I am working on since now so that we can remove our dependency on the old extension, which can't be installed in the browser.
