### ISSUE TITLE
Multi-line string syntax highight

### ISSUE THREAD

**Issue by AlienKevin** [elm-tooling/elm-language-client-vscode#58]
Triple-quoted multi-line strings are not highlighted properly.
One problem appears when there are `'`s in `"`

![image](https://user-images.githubusercontent.com/22850071/71492434-19bd3800-2805-11ea-99ea-33134a703450.png)

Another problem appears when `"` are unmatched

![image](https://user-images.githubusercontent.com/22850071/71492616-97357800-2806-11ea-9c4a-c8a237017e86.png)

Environment:
vscode 1.41.0
windows 10

**Comment by Razzeee** [comment]
Split to https://github.com/elm-tooling/elm-language-client-vscode/issues/61
