### ISSUE TITLE
Formatting does not working

### ISSUE THREAD

**Issue by fernandoxu** [elm-tooling/elm-language-client-vscode#59]
Formatting does not working even I use shift+alt+f.
Here are my settings:
![未命名1577563911](https://user-images.githubusercontent.com/20871468/71549086-8e08fe80-29f2-11ea-9724-3ac892571a47.png)
I can use elm-format on command line and it works
![未命名1577564606](https://user-images.githubusercontent.com/20871468/71549114-05d72900-29f3-11ea-9f1b-259e6281c9b1.png)
##  my environment

* Version used: 0.7.4,elm-format 0.8.2
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.41
* Environment name and version (e.g. node.js 5.4): node.js v12.14.0
* Operating System and version: windows10

**Comment by jluckyiv** [comment]
I am having the same issue on macOS.

## my environment

Version used: 0.7.4,elm-format 0.8.2
Editor name and version (e.g. VSCode 1.36.1): VSCode 1.41.1
Environment name and version (e.g. node.js 5.4): node.js v12.14.0
Operating System and version: macOS 10.15.2 (19C57), but I had the same issue in 10.14.x.

**Comment by Razzeee** [comment]
Can you try the same with https://github.com/rtfeldman/elm-spa-example ?
That's a way for me to make sure it's not due to your project structure.

**Comment by fernandoxu** [comment]
@Razzeee It works! 😱
My project is a clone of [https://github.com/rtfeldman/elm-0.19-workshop](https://github.com/rtfeldman/elm-0.19-workshop),is it because something has a different version?

**Comment by Razzeee** [comment]
It will work fine, if you directly open up a part like https://github.com/rtfeldman/elm-0.19-workshop/tree/master/advanced/part1

It's what's described in https://github.com/elm-tooling/elm-language-client-vscode/issues/30, so I will close this for now. :)
