### ISSUE TITLE
Option to disable running tests on every change

### ISSUE THREAD

**Issue by shamansir** [elm-tooling/elm-language-client-vscode#60]
My workflow is usually to run tests manually. In some cases they take time to perform, in some cases I run them in CI on push, in some cases the project has no tests. Also I use the external terminal application in most cases.

## Expected Behavior
The setting to disable running `elm-test` on every change.

## Current Behavior
On every change in the Elm or tests code, the VSCode Terminal Window opens (even when I close it, it ensures that it reopens) and starts running the tests. Setting Elm Test path in options to `/dev/null` does not help (show the warning that binary is not accessible but still finds `elm-test` in `./node_modules`), removing task from Terminal also does not help.

It also removes cursor focus from the current editor window, since I have _AutoSave_ on and so it actually runs for every symbol being entered.

## Your Environment

* Version used: 0.7.4
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.41.1
* Environment name and version (e.g. node.js 5.4):
* Operating System and version: macOS Mojave

**Comment by shamansir** [comment]
It is also defined in my `package.json` and in my `./.vscode/tasks.json` file. And when I remove it from the list in `tasks.json` and restart VSCode, the value gets back in the list when the extension is activated (could be another reason, at least looks like that).

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "test",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

Could be connected to: https://discourse.elm-lang.org/t/elm-test-watch-on-a-package-when-using-vs-code-causes-problems/3406

**Comment by Razzeee** [comment]
We don't actually run tests in this extension yet, we only compile them.
So it sounds like what you see is coming from some other extension. Can you check and retest your problem with ONLY our extension installed/enabled?

**Comment by shamansir** [comment]
Indeed it was the `elm-test-runner` extension I forgot that I have installed previously (and it wasn't triggering the tests before only since `elm-test` wasn't installed on this machine before). Please sorry for the confusion and thank you for the plugin development!
