### ISSUE TITLE
After running elm make,every time when I ctrl+s to save the fill I will got a windows script host error.

### ISSUE THREAD

**Issue by fernandoxu** [elm-tooling/elm-language-client-vscode#62]
## Steps to Reproduce (for bugs)

1.

>  elm make src/Main.elm --output elm.js

2. Edit a .elm file and save it. 
3.  Windows Script Host shows "Microsoft JScript 编译错误(compilation error)"
![未命名1578033271](https://user-images.githubusercontent.com/20871468/71710874-47bfff00-2e39-11ea-8e72-d5723d644ada.png)

## Your Environment

* Version used:
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.14.1
* Environment name and version (e.g. node.js 5.4):node.js v12.14.0
* Operating System and version: windows 10, 19041.1

**Comment by fernandoxu** [comment]
I found a solution on stackoverflow but it's not exactly the same.
 [Elm Make starts Windows Script Host and gives error?](https://stackoverflow.com/questions/35987134/elm-make-starts-windows-script-host-and-gives-error)

**Comment by Razzeee** [comment]
I don't think this is an issue with the vscode extension

**Comment by fernandoxu** [comment]
@Razzeee 
But I tested with other editors(webstorm,atom) on my computer and this issue did not appear.

**Comment by Razzeee** [comment]
Do you run `elm make src/Main.elm --output elm.js` in those editors too?

Your problem is just that you named it `elm.js` and windows does some weird stuff. Just name it something else, that doesn't match the elm executables name.
