### ISSUE TITLE
Saving file with formatOnSave enabled goes timeout, while "Format Document" command works

### ISSUE THREAD

**Issue by neslinesli93** [elm-tooling/elm-language-client-vscode#63]
Hi! I've just migrated to this plugin, after the deprecation of the old one. I've noticed a strange behaviour with the formatter, that only happens with large files (~4k lines).

After doing edits to said files and saving, if `editor.formatOnSave` is enabled, nothing happens and this message appears in the console: `WARN Aborted format on save after 750ms`. If i open the commands list and hit `Format Document`, it works instantly.

After digging in the code, it looks like this is the [offending line](https://github.com/elm-tooling/elm-language-server/blob/master/src/providers/documentFormatingProvider.ts#L40). After digging in the `elm-language-server` repo, it looks like we are not alone: https://github.com/elm-tooling/elm-language-server/issues/85.

Do you have a plan for this? Like an option to disable the text diffing, since it looks like it's only used for elm-analyse diagnostics, if I'm not missing anything...

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Editor name and version (e.g. VSCode 1.36.1): 
* Environment name and version (e.g. node.js 5.4):
* Operating System and version:

**Comment by Razzeee** [comment]
It's always used to diff down your formatted file. As completely replacing the file would also reset your cursor and scroll position.

**Comment by Razzeee** [comment]
Historically the previous issues all pointed in the direction of elm-format being slow. I'm also surprised, that you get a different result from the command. Do you have other plugins installed that could feed into this?

You can also increase the timeout to get around that.

**Comment by neslinesli93** [comment]
I've increased the timeout to 5000 ms, and disabled all the extensions but yours. The result is the same: the format on save times out

**Comment by Razzeee** [comment]
You probably can't share the offending file?

In that case the best thing would be, if you set some debug points and look at the data and what takes how long. Or if it's a bug in the compare/ it returns something wrong.

**Comment by Razzeee** [comment]
Can you try again with the latest version of vscode? The timeout behavior was removed and replaced with a new system.
