### ISSUE TITLE
Add not equal "/=" operator to list of infix_op

### ISSUE THREAD

**Issue by flew2bits** [elm-tooling/elm-language-client-vscode#65]
The elm.json grammar currently treats "/=" as the divide operator followed by an assignment operator. Since these are colored differently, when using fonts with ligatures, this causes the glyph to show incorrectly.

In lines 487-490 of elm.json, changing the match from:
`"match": "(<\\||<=|\\|\\||&&|>=|\\|>|\\|\\=|\\=\\=|\\|\\.|\\|\\=|\\+\\+|\\:\\:|\\+|\\-|\\*|\\/|\\/\\/|\\^|>>|<<|<|>|%)"`
to
`"match": "(<\\||<=|\\|\\||&&|>=|\\|>|\\|\\=|\\=\\=|\\|\\.|\\|\\=|\\+\\+|\\:\\:|\\+|\\-|\\*|\\/\\=|\\/|\\/\\/|\\^|>>|<<|<|>|%)"`
fixes the issue. The string `"|\\/\\="` was added just before  `"|\\/"`.

**Comment by Razzeee** [comment]
While I agree that it should be added (see https://github.com/elm-tooling/elm-language-client-vscode/pull/68), I can't replicate the ligatures to look wrong with `Fira Code` on linux. Can you post a screenshot?

**Comment by flew2bits** [comment]
Sure. I've attached two screenshots. The first one shows "/=" with the current configuration. The second one shows it with the change I suggested. This is using the Jetbrains Mono font.

![WithoutChange](https://user-images.githubusercontent.com/4671044/73107345-9fe3a180-3ecb-11ea-8d40-5c75a83792d8.PNG)
![WithChange](https://user-images.githubusercontent.com/4671044/73107346-9fe3a180-3ecb-11ea-8e67-22d9b1a43d45.PNG)

**Comment by flew2bits** [comment]
I just tested it with Fira Code, as well, and it does the same thing; it's because the '=' is a different color since it gets tagged as an assignment operator.

**Comment by flew2bits** [comment]
I just looked at #68, and I don't think it will work correctly. The "/=" option has to come before "/" otherwise it won't get recognized as a whole.

**Comment by Razzeee** [comment]
I moved all single char matches to the back now. I'm still not seeing the bug locally, but I'm going to trust you. A last look at #68 would be awesome.
