### ISSUE TITLE
Multiple Elm Apps Within the Same Workspace Causes the Extension to Behave Unexpectedly

### ISSUE THREAD

**Issue by nahiyan** [elm-tooling/elm-language-client-vscode#66]
## Expected Behavior
It's not uncommon to have projects where multiple languages, frameworks, etc used to generate the final product. In this sense, it's nothing strange to have multiple Elm apps within the same workspace. The extension is expected to distinguish between the separate Elm apps and treat them as such.

## Current Behavior
The extension treats separate Elm apps in a workspace as a single app in the sense that it generates Elm object files for every single Elm file there is in the workspace, and places them in every single Elm app's "elm-stuff" directory, thus creating a mess! Each app's "elm-stuff" directory should only have its own object files, not object files of other apps in the workspace.

On the other side - analysis, formatting, etc only works for one Elm app in the workspace, not others. Analysis report is generated for the other apps only during startup/reload of window, and never changes afterwards.

## Possible Solution
The extension can simply identify separate Elm apps within the workspace and treat them separately.

## Steps to Reproduce
1. Create a new VSCode workspace or open an existing one
2. Add multiple Elm apps

## Context
I've recently tried creating a Phoenix (Elixir-based) app, with two Elm apps powering a portion of the frontend, all within a single workspace. Since all these are connected extensively, it'd be a waste of time to jump between workspaces for each Elm app. Having multiple Elm apps within the same workspace seems to cause this issue only.

## Your Environment
* Version used: 0.7.4
* Editor name and version: VSCode 1.41.1
* Environment name and version: node.js 11.0.0
* Operating System and version: macOS 10.14.6 (Mojave)
* Elm version: 0.19.0

**Comment by Razzeee** [comment]
Duplicate of https://github.com/elm-tooling/elm-language-client-vscode/issues/30


>The extension treats separate Elm apps in a workspace as a single app in the sense that it generates Elm object files for every single Elm file there is in the workspace, and places them in every single Elm app's "elm-stuff" directory, thus creating a mess! Each app's "elm-stuff" directory should only have its own object files, not object files of other apps in the workspace.

Just to be clear, we don't create anything in the `elm-stuff` folder. But elm or elm-analyze might.

**Comment by nahiyan** [comment]
Rebuilding the extension with the elm-language-server replaced with [sentience's fix](https://github.com/sentience/elm-language-server/tree/fix-multiple-elm-workspaces) worked for me.

**Comment by sentience** [comment]
@nahiyan Great to hear! We're getting ready to merge and release this change any day now.

**Comment by nahiyan** [comment]
@sentience Thank you so much for the fix. Since this fix is going to be merged and released, I think it's time to close this issue.
