### ISSUE TITLE
Only syntax highlighting works

### ISSUE THREAD

**Issue by jvmap** [elm-tooling/elm-language-client-vscode#67]
After installing Visual Code and this extension, syntax highlighting works for .elm files. However, none of the more advanced features work. 
Ctrl+Shift+O just gives "No symbol information for file".

I suspect that the language server is not running, but I cannot tell why this is the case. I don't see any error messages.

## Expected Behavior
I'm able to use features like rename (F2) and go to definition (F12).

## Current Behavior
Nothing happens when I press F2 or F12.

## Steps to Reproduce (for bugs)

1. Install VSCode
2. Install the extension from within VSCode (Ctrl + Shift + X, install elmtooling.elm-ls-vscode)
3. Open a .elm file, for example the one attached.

## Context

I also installed the latest elmtooling from source (using the steps described at the end of the readme). I can successfully run the extension in debug mode. It shows the same behavior as the version from marketplace. I switched on 'break on all exceptions', 'uncaught exceptions' and 'break on promise rejects' before loading the .elm file. I get one promise reject related to git, but nothing related to elmtooling.

## Your Environment

VSCode Version: 1.41.1 (user setup)
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Example ELM file to reproduce the problem:
------------------------------------------------
```elm
import Browser
import Html exposing (Html, button, div, text)
import Html.Events exposing (onClick)

main =
  Browser.sandbox { init = 0, update = update, view = view }

type Msg = Increment | Decrement

update msg model =
  case msg of
    Increment ->
      model + 1

    Decrement ->
      model - 1

view model =
  div []
    [ button [ onClick Decrement ] [ text "-" ]
    , div [] [ text (String.fromInt model) ]
    , button [ onClick Increment ] [ text "+" ]
    ]
```

**Comment by Razzeee** [comment]
You will need to have a valid elm project, that includes an `elm.json`. You should be able to easily create that with `elm init`. :)

**Comment by jvmap** [comment]
Duh. I had an elm.json (one level higher than the .elm file), but I just opened the .elm file with VSCode instead of the folder. It works when I open the project folder in VSCode and then open the .elm file from within VSCode. Thanks!
