### ISSUE TITLE
Broken in VSCode 1.84

### ISSUE THREAD

**Issue by TheOddler** [elm-tooling/elm-language-client-vscode#718]
## Expected Behavior

The Elm LS works in VSCode.

## Current Behavior

The plugin fails to load with this error:

```
[Error - 12:24:22 PM] Unhandled Rejection at: Promise [object Promise] reason:, TypeError: Failed to parse URL from /nix/store/bq83f9aqgxs4lf9fll3g3sz5hv2m2p31-vscode-extension-Elmtooling-elm-ls-vscode-2.6.0/share/vscode/extensions/Elmtooling.elm-ls-vscode/server/node_modules/web-tree-sitter/tree-sitter.wasm
```

I checked, and the tree-sitter.wasm file does exist.

## Steps to Reproduce (for bugs)

1. Start VS Code
2. Look in the `Output` console at the output for Elm
3. Error, and no LS diagnostics are shown in the editor.

## Your Environment

* Version used: v2.6.0
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.84.2
* Environment name and version (e.g. node.js 5.4): node v18.14.0
* Operating System and version: NixOs 23.11

**Comment by TheOddler** [comment]
Found a similar issue: https://github.com/elm-tooling/elm-language-server/issues/692

So the bug is back?

I tried updating to node 20.9, but same issue persists.

**Comment by TheOddler** [comment]
I just tried reverting to an older version of VSCode, and now it works again.

So:

* :-1:  Broken in VSCode 1.84.2
* :+1: Works in VSCode 1.78.2

Not sure why, maybe they use a different node version internally?

**Comment by TheOddler** [comment]
Looks like VSCode 1.78.2 uses Node.js 16.17.1,
and VSCode 1.84.2 uses Node.js 18.15.0.

From https://github.com/elm-tooling/elm-language-server/issues/692 it seems that the elm-language-server works with Node 16, but not Node 18. So that explains why it's broken now.

From that same issue, looks like the Elm LS works again in Node 20, so I guess we'll have to wait until Vscode updates to that? I guess that will be a while though, but for now downgrading VSCode worked.

**Comment by razzeee** [comment]
I would hope for node 18 to also work, but there has been a python patch, that is needed to successfully build a new tree sitter version and last I checked it still wasn't in stable.

**Comment by razzeee** [comment]
There's a new build, please try that

**Comment by TheOddler** [comment]
Updated to VSCode v1.84.2 and elmtooling.elm-ls-vscode v2.8.0, and everything works! Thank you!
