### ISSUE TITLE
Problems tab does not update when file is deleted

### ISSUE THREAD

**Issue by jonsa** [elm-tooling/elm-language-client-vscode#72]
If a file has entries in the problems tab `Ctrl`+`Shift`+`M` and the file is deleted the reported issues still remain. To remove them I have to run `Reload Window`.

## Expected Behavior
When a file which has reported problems is removed I expect the problems to go away.

## Current Behavior
Reported problems for deleted files will remain until the entire editor is refreshed.

## Steps to Reproduce (for bugs)
1. Create an empty `*.elm` file which will report `WEIRD DECLARATION - I am trying to parse ...`
2. Delete the file
3. The error will persist in the problems tab.

## Your Environment
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
Elm: 1.19.1
Elm extension: 0.8.0

**Comment by Razzeee** [comment]
Fixed via https://github.com/elm-tooling/elm-language-server/commit/769796efe8d057e4d6b35ae0f7e538d2145c66cc

But we also need to figure out a way to delete the files from the ast.
