### ISSUE TITLE
[Feature Request] - toggle on / off various features

### ISSUE THREAD

**Issue by gDelgado14** [elm-tooling/elm-language-client-vscode#79]
### Context

Love how well the elm plugin works, however I **personally** (I really want to stress that this is just a preference thing) am not a fan of injected links that appear above variables and types. See the following screenshot as an example:

<img width="370" alt="Screen Shot 2020-02-16 at 7 02 51 PM" src="https://user-images.githubusercontent.com/10621548/74615462-03d64000-50ef-11ea-89a6-f16e4a3b6016.png">

### Desired Outcome

It would be great if there was a way for developers to pick and choose which functionality they'd like to have on, and which they'd like to have off.

**Comment by Razzeee** [comment]
Please refer to https://github.com/elm-tooling/elm-language-client-vscode/issues/17#issuecomment-544207163
