### ISSUE TITLE
Windows ScriptHost error for JS file on save

### ISSUE THREAD

**Issue by chrisnawrot** [elm-tooling/elm-language-client-vscode#82]
1. Start a new project with elm init
2. Make a main module in src
3. Use elm-make to output a JS file (named elm.js) to the base directory of the elm project
4. Save the main elm module in vs code

I observe the following:

![image](https://user-images.githubusercontent.com/439683/74969222-24054800-53ea-11ea-9aa6-3c2e875f2bd1.png)

If the output of elm-make is in a nested directory, then the error message doesn't occur.

Tried disabling the extension and could not repro the issue.

**Comment by Razzeee** [comment]
That's a problem due to windows getting confused between `elm.js` and `elm.exe`. I would recommend to not name your bundle `elm.js`, mostly due to that behaviour of windows.

I guess it might help if we call `elm.exe` on windows instead of `elm`

**Comment by chrisnawrot** [comment]
Fair enough. Just FYI, I was following along with Richard Feldman's book (Elm in Action, Manning) when I ran into the issue. The book doesn't suggest making elm.js in the base dir of a project, but that's how one of its first coding/building exercises is written. I imagine this issue will crop-up again sooner or later since this is such a great extension for writing Elm, and Feldman's book is getting attention. Thanks!

**Comment by Razzeee** [comment]
Yeah, I'm not sure if @rtfeldman is aware of that bug on windows or if he's still able to change the book.

**Comment by Razzeee** [comment]
to explain, it will also happen when you try to call elm via `elm` in that directory on windows.

**Comment by sogaiu** [comment]
FWIW, in limited testing, removing `.JS` from the environment variable `PATHEXT` seems to be a work-around on Windows.

Here's some detail:

```
C:\Users\user\Desktop\elm-in-action>echo %PATHEXT%
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

C:\Users\user\Desktop\elm-in-action>set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC

C:\Users\user\Desktop\elm-in-action>echo %PATHEXT%
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC

C:\Users\user\Desktop\elm-in-action>elm make src\PhotoGroove.elm
Success!

    PhotoGroove ---> index.html


```

If VSCode is started from the same `CMD.exe` session, the Window Script Host dialog error (800A1391) does not occur for me for saving elm files.
C:\Users\user\Desktop\elm-in-action>C:\Users\user\scoop\apps\vscode\current\bin\code
```
