### ISSUE TITLE
Elm files never format on save

### ISSUE THREAD

**Issue by pnaylor** [elm-tooling/elm-language-client-vscode#86]
## Expected Behavior

Format on save.

## Current Behavior

Elm files never format on save. Tried setting `Elm Format Path` and was able to use  `alt + shift + f` formatting on elm doc after, but still no format on save.

## Steps to Reproduce (for bugs)

1. Installed plugin in existing version of VS Code
2. Ran `npm install -g elm-test elm-format` to be sure
3. Tried testing format on save without luck
4. Deleted vs code plugins folder and tried reinstalling just this one, suspecting a possible conflict
5. Still no format on save
6. Tried setting `Elm Format Path` to `c:\Program Files\nodejs\elm-format`
7. Still no format on save, but was able to use `alt + shift + f` formatting (only after specifying this setting)

## Context

Syntax highlighting and some compiler checks seem to be working but can't get format on save working. Also had the previous deprecated VSC Elm extension before switching to this one and had the same formatting issue before as well.

## Your Environment

* Version used: 0.9.3
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.42.1
* Environment name and version (e.g. node.js 5.4): node 10.16.0
* Operating System and version: Win 10 Pro

**Comment by Razzeee** [comment]
Can you/did you test this with the elm spa example? https://github.com/rtfeldman/elm-spa-example

**Comment by pnaylor** [comment]
I did, same result. Was thinking of trying to debug from the plugin code, but didn't really know where to start. Can't find any other log indications of why it might not be working so far.
Much appreciated

**Comment by Razzeee** [comment]
The `Output` panel should offer you an entry with `Elm (Project Name)` in the dropdown.

**Comment by NikosEfthias** [comment]
where is the output panel ? I dont even have elm:format action in my case and I always get error message saying server crashed more than "x" times not resatrting when I try to fix things I was trying to upgrade to vscode from vim but apparetnly vim plugin provides a better experience then this

**Comment by Razzeee** [comment]
Goto the menu on top then `View -> Output`

**Comment by aotarola** [comment]
if `alt + shift + f` works for you, then you are probably not triggering format on save, check your settings to have 
```json
"editor.formatOnSave": true,
```

**Comment by pnaylor** [comment]
Wow, you were right @aotarola, thank you! Can't believe I had not found that in my searching on the problem. Hopefully this will help someone else in the future at least now as well though. Cheers
