### ISSUE TITLE
Big files is processed too slow

### ISSUE THREAD

**Issue by yarus23** [elm-tooling/elm-language-client-vscode#89]
## Current Behavior

After including Tailwind css support Elm file VsCode starts indexing Elm and it takes too long (10 minutes may be and eats CPU too)
Test project [test.zip](https://github.com/elm-tooling/elm-language-client-vscode/files/4363888/test.zip)

## Steps to Reproduce (for bugs)

1. Include in
 Main.elm for example 'import TLWND exposing(..)'
2. Wait a bit

## Your Environment

* Version 9.4
* VsCode 1.43.1
* Windows 10x64

**Comment by Razzeee** [comment]
Seems to be caused by this for loop https://github.com/elm-tooling/elm-language-server/blob/9466b98df682c434f7cdad65f03ce40928531dc6/src/util/treeUtils.ts#L167-L177

Or specifically the `findFunction` function call, as it gets called for every node

**Comment by Razzeee** [comment]
See the linked PR for a possible fix

**Comment by Razzeee** [comment]
The other part of this being slow seems to be resolved if you disable
elm-analyse. So it might make sense to test that too and create an issue
over there.
