### ISSUE TITLE
Exposed types not available in code completion

### ISSUE THREAD

**Issue by lovebug356** [elm-tooling/elm-language-client-vscode#92]
When I'm importing types defined in other elm files. I expect that code completion suggests these already existing types.

Given, I have two files in the same folder:
View.elm
```
module View exposing (..)


type MainView
    = MainView String
```

Main.elm
```
module Main exposing (createView)

-- This is the line I would like to insert with assistance from code completion.
-- import View exposing (MainView)


createView : MainView -> String
createView (MainView view) =
    view

```

## Expected Behavior
when I type `import View exposing MainV` I expect it suggests `MainView`.

## Current Behavior
Code completion is suggesting `View.MainView`, providing the invalid code.
```import View exposing (View.MainView)```

![exposing-wrong-name](https://user-images.githubusercontent.com/51261/78138569-68432980-7427-11ea-84dc-455d2a976ab7.png)

At some other moments when I try to reproduce, I do not have any completion available:
![rename-pos-4](https://user-images.githubusercontent.com/51261/78141384-b6f2c280-742b-11ea-8b3b-ebec2afd4ec0.png)

## Your Environment
* Version used: Elm 0.10.0
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.42.1
* Operating System and version: ArchLinux

**Comment by Razzeee** [comment]
Good catch, thank you!
