### ISSUE TITLE
Completion suggestion breaks on nested models

### ISSUE THREAD

**Issue by tiagoroldao** [elm-tooling/elm-language-client-vscode#95]
> Caveat: JS developer trying out Elm, so I may be doing something very silly, but to my knowledge it appears to be a code issue, rather than a user issue.

## Expected Behavior
Completion suggestions should work with nested models.

## Current Behavior
This works:
<img width="904" alt="Screenshot 2020-04-06 09 41 00" src="https://user-images.githubusercontent.com/1634026/78534749-3e08b780-77eb-11ea-9947-07a1837b30c7.png">

This does not:
<img width="841" alt="Screenshot 2020-04-06 09 41 10" src="https://user-images.githubusercontent.com/1634026/78534492-cd619b00-77ea-11ea-993e-fd53a1a6fa9d.png">

Above I would hope to see `model.url.path`, etc etc

## Steps to Reproduce (for bugs)
1. Use the Browser.application snipper
2. Access `model.url` as shown above
2. Attempt to get `model.url.foo` properties to be suggested

## Context
Simple usage, everything installed and running as normally to my best knowledge

## Your Environment
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by Razzeee** [comment]
Yes, we're currently working to improve this please refer to https://github.com/elm-tooling/elm-language-server/pull/251 for updates

**Comment by tiagoroldao** [comment]
What a nice way to say "duplicate" 😄 
Apologies, the terminology escapes me still, so didn't find it searching. Closing this, following the other.

**Comment by Razzeee** [comment]
It's not easy to find, due to this project being separated into two issue trackers :)
