### ISSUE TITLE
Different color coding than ellie

### ISSUE THREAD

**Issue by wibrt** [elm-tooling/elm-language-client-vscode#96]
Using this plugin, the color coding is different than on on ellie:
for example:
https://elm-lang.org/examples/time
compare this
with the same code in vscode with plugin

(Especially Upper vs lower string and meaning)

## Expected Behavior
it would be better? to have the color coding from ellie

## Current Behavior
It is different, with less info about the meaning of each literal in the code

## Possible Solution
Copy the syntax highlighting from ellie?

## Steps to Reproduce (for bugs)
1.Goto https://elm-lang.org/examples/time
2.c/p in your vscode with this plugin enabled (oif this project)
3.See the difference

## Your Environment
0.9.1 from marketplace

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2020-01-19T05:18:46.103Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.4.0-0.bpo.4-amd64

**Comment by Razzeee** [comment]
Only difference I can spot is modules and types not getting colored
![image](https://user-images.githubusercontent.com/5943908/78942777-ab9e3780-7aba-11ea-8a01-f6b2d4c177c8.png)


Anyway, good news is, I was about to work on improving syntax coloring anyway, as semantic highlighing just landed in vscode
https://code.visualstudio.com/updates/v1_44#_semantic-tokens-provider-api
https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

**Comment by wibrt** [comment]
good news, looking forward to it
