### ISSUE TITLE
Run Debug does not work

### ISSUE THREAD

**Issue by wibrt** [elm-tooling/elm-language-client-vscode#97]
## Expected Behavior
Being able to run/debug after installing this elm-language-client-vscode,
with all the steps followed of the readme

## Current Behavior
There is only one runtime available : node, i don't know if this is normal.
If this is normal, then running the program gives an error about outFiles.
With a suggestion for launch.json

Within the terminal everything works, but not within vscode.

The current automatic launch.json file looks like this:

> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "type": "node",
>             "request": "launch",
>             "name": "Launch Program",
>             "skipFiles": [
>                 "<node_internals>/**"
>             ],
>             "program": "${file}"
>         }
>     ]
> }

## Your Environment
* elm@0.19.1-3
* elm-format@0.8.3
* elm-test@0.19.1-revision2
* elm-analyse@0.16.5
* VScode Version: 1.44.0
* Commit: 2aae1f26c72891c399f860409176fe435a154b13
* Date: 2020-04-09T10:44:46.342Z
* Electron: 7.1.11
* Chrome: 78.0.3904.130
* Node.js: 12.8.1
* V8: 7.8.279.23-electron.0
* OS: Linux x64 5.4.0-0.bpo.4-amd64 snap

**Comment by Razzeee** [comment]
Hey there,

launch configs are not provided right now. You can run the compiler by saving a file, but that won't actually run your code. You could create a task and launch that from your launch config. But we don't provide those yet, they could be included, if you would like to work on them. 

The thing that kept me from doing that so far is, that most of configs for elm seem to be pretty different. Some might be using elm directly, other elm-live, others will just call their hosting language like c# or elixir. But I guess we could do configs which cover the first two?

**Comment by Razzeee** [comment]
Closing due to no feedback
