### ISSUE TITLE
Insert inferred type signatures

### ISSUE THREAD

**Issue by georgefst** [elm-tooling/elm-language-client-vscode#99]
The IntelliJ plugin says it can 'Generate type annotation for un-annotated functions'. This ability is something I really miss from my Haskell setup. Are there any plans to add it?

**Comment by Razzeee** [comment]
Yes, but reimplementing type inference hasn't been as simple as I would
have liked. I'm also struggling to find time to work on it. You can check
the type inference branch on the server repo.

**Comment by NigelThorne** [comment]
I'd love to have this. Can I help? Is there a branch I can look at?

**Comment by Razzeee** [comment]
You can look at https://github.com/elm-tooling/elm-language-server/pull/310 which is working, but not quiet ready. I guess it would be best to talk about specifics in that PR.

**Comment by Razzeee** [comment]
This is included in the latest release.
